- name: Create directory
  file:
    path: /opt/asset-registry
    state: directory
    mode: '0755'


- name: Template docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: /opt/asset-registry/docker-compose.yml
    mode: '0644'

- name: Stop existing services gracefully
  community.general.docker_compose:
    project_src: /opt/asset-registry
    timeout: 180
    state: present
    stopped: yes

- name: Tear down existing services
  community.general.docker_compose:
    project_src: /opt/asset-registry
    state: absent

- name: Run services
  community.general.docker_compose:
    project_src: /opt/asset-registry
    timeout: 180
    state: present
    pull: yes
