package congestioncontrol

import (
	"github.com/iotaledger/goshimmer/packages/protocol/congestioncontrol/icca/scheduler"
	"github.com/iotaledger/hive.go/runtime/event"
)

type Events struct {
	Scheduler *scheduler.Events

	event.Group[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.CreateGroupConstructor(func() (newEvents *Events) {
	return &Events{
		Scheduler: scheduler.NewEvents(),
	}
})
