package chain

import (
	"github.com/iotaledger/hive.go/core/generics/event"

	engine2 "github.com/iotaledger/goshimmer/packages/protocol/chain/engine"
)

type Events struct {
	SwitchedEngine *event.Linkable[*engine2.Engine, Events, *Events]

	Engine *engine2.Events

	event.LinkableCollection[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.LinkableConstructor(func() (newEvents *Events) {
	return &Events{
		SwitchedEngine: event.NewLinkable[*engine2.Engine, Events, *Events](),

		Engine: engine2.NewEvents(),
	}
})
