package heartbeat

import "crypto/sha256"

const (
	MARSHALED_PACKET_HEADER = 0x05

	MAX_MARSHALED_TOTAL_SIZE = MARSHALED_PACKET_HEADER_SIZE + MARSHALED_OWN_ID_SIZE +
		MARSHALED_OUTBOUND_IDS_LENGTH_SIZE + 4*MARSHALED_OUTBOUND_ID_SIZE +
		MARSHALED_INBOUND_IDS_LENGTH_SIZE + 4*MARSHALED_INBOUND_ID_SIZE

	MARSHALED_PACKET_HEADER_START = 0
	MARSHALED_PACKET_HEADER_SIZE  = 1
	MARSHALED_PACKET_HEADER_END   = MARSHALED_PACKET_HEADER_START + MARSHALED_PACKET_HEADER_SIZE

	MARSHALED_OWN_ID_START = MARSHALED_PACKET_HEADER_END
	MARSHALED_OWN_ID_SIZE  = sha256.Size
	MARSHALED_OWN_ID_END   = MARSHALED_OWN_ID_START + MARSHALED_OWN_ID_SIZE

	MARSHALED_OUTBOUND_IDS_LENGTH_START = MARSHALED_OWN_ID_END
	MARSHALED_OUTBOUND_IDS_LENGTH_SIZE  = 1
	MARSHALED_OUTBOUND_ID_SIZE          = sha256.Size
	MARSHALED_OUTBOUND_IDS_LENGTH_END   = MARSHALED_OUTBOUND_IDS_LENGTH_START + MARSHALED_OUTBOUND_IDS_LENGTH_SIZE

	MARSHALED_INBOUND_IDS_LENGTH_SIZE = 1
	MARSHALED_INBOUND_ID_SIZE         = sha256.Size
)
