export const COLOR = {
    MESSAGE_PENDING: '#b9d6dc',
    MESSAGE_CONFIRMED: '#5296A5',
    TRANSACTION_PENDING: '#e5daa3',
    TRANSACTION_CONFIRMED: '#F0C808',
    TIP: '#A31621',
    NODE_SELECTED: '#61E294',
    NODE_BORDER_SELECTED: '#61E294',
    NODE_UNKNOWN: '#b58900',
    LINK_WEAK: '#E7DFC6',
    LINK_STRONG: '#36636D',
    LINK_SHALLOW_LIKED: '#10f008',
    LINK_SHALLOW_DISLIKED: '#f00808',
    LINK_FUTURE_CONE: '#EF8354',
    LINK_PAST_CONE: '#B91372',
    MARKER: '#05445E'
};

export const LINE_TYPE = {
    STRONG: '-',
    WEAK: '5 2',
    SHALLOW_LIKED: '2 3',
    SHALLOW_DISLIKED: '2 3'
};

export const LINE_WIDTH = {
    STRONG: 3,
    WEAK: 2,
    SHALLOW_LIKED: 2,
    SHALLOW_DISLIKED: 2
};

export const VERTEX = {
    SIZE_DEFAULT: 30,
    SIZE_SELECTED: 35,
    ROUNDED_CORNER: 5,
    SELECTED_BORDER_WIDTH: 4,
    MARKER_SIZE: 4
};

export const CONFLICT = {
    WINNER_COLOR: '#739A25',
    LOOSER_COLOR: '#A31621',
    WIDTH: 6,
};
