package mempool

import (
	"context"

	"github.com/iotaledger/goshimmer/packages/protocol/engine/ledger/mempool/conflictdag"
	"github.com/iotaledger/goshimmer/packages/protocol/engine/ledger/utxo"
	"github.com/iotaledger/hive.go/core/slot"
	"github.com/iotaledger/hive.go/ds/advancedset"
	"github.com/iotaledger/hive.go/runtime/event"
)

// region Events ///////////////////////////////////////////////////////////////////////////////////////////////////////

// Events is a container that acts as a dictionary for the existing events of a MemPool.
type Events struct {
	// TransactionStored is an event that gets triggered whenever a new Transaction is stored.
	TransactionStored *event.Event1[*TransactionStoredEvent]

	// TransactionBooked is an event that gets triggered whenever a Transaction is booked.
	TransactionBooked *event.Event1[*TransactionBookedEvent]

	// TransactionInclusionUpdated is an event that gets triggered whenever the inclusion time of a Transaction changes.
	TransactionInclusionUpdated *event.Event1[*TransactionInclusionUpdatedEvent]

	// TransactionAccepted is an event that gets triggered whenever a Transaction is accepted.
	TransactionAccepted *event.Event1[*TransactionEvent]

	// TransactionOrphaned is an event that gets triggered whenever a Transaction is orphaned.
	TransactionOrphaned *event.Event1[*TransactionEvent]

	// TransactionRejected is an event that gets triggered whenever a Transaction is rejected.
	TransactionRejected *event.Event1[*TransactionMetadata]

	// TransactionForked is an event that gets triggered whenever a Transaction is forked.
	TransactionForked *event.Event1[*TransactionForkedEvent]

	// TransactionConflictIDUpdated is an event that gets triggered whenever the Conflict of a Transaction is updated.
	TransactionConflictIDUpdated *event.Event1[*TransactionConflictIDUpdatedEvent]

	// TransactionInvalid is an event that gets triggered whenever a Transaction is found to be invalid.
	TransactionInvalid *event.Event1[*TransactionInvalidEvent]

	OutputCreated  *event.Event1[utxo.OutputID]
	OutputSpent    *event.Event1[utxo.OutputID]
	OutputRejected *event.Event1[utxo.OutputID]

	// Error is event that gets triggered whenever an error occurs while processing a Transaction.
	Error *event.Event1[error]

	ConflictDAG *conflictdag.Events[utxo.TransactionID, utxo.OutputID]

	event.Group[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.CreateGroupConstructor(func() (newEvents *Events) {
	return &Events{
		TransactionStored:            event.New1[*TransactionStoredEvent](),
		TransactionBooked:            event.New1[*TransactionBookedEvent](),
		TransactionInclusionUpdated:  event.New1[*TransactionInclusionUpdatedEvent](),
		TransactionAccepted:          event.New1[*TransactionEvent](),
		TransactionOrphaned:          event.New1[*TransactionEvent](),
		TransactionRejected:          event.New1[*TransactionMetadata](),
		TransactionForked:            event.New1[*TransactionForkedEvent](),
		TransactionConflictIDUpdated: event.New1[*TransactionConflictIDUpdatedEvent](),
		TransactionInvalid:           event.New1[*TransactionInvalidEvent](),
		OutputCreated:                event.New1[utxo.OutputID](),
		OutputSpent:                  event.New1[utxo.OutputID](),
		OutputRejected:               event.New1[utxo.OutputID](),
		Error:                        event.New1[error](),

		ConflictDAG: conflictdag.NewEvents[utxo.TransactionID, utxo.OutputID](),
	}
})

// endregion ///////////////////////////////////////////////////////////////////////////////////////////////////////////

// region TransactionStoredEvent ///////////////////////////////////////////////////////////////////////////////////////

// TransactionStoredEvent is a container that acts as a dictionary for the TransactionStored event related parameters.
type TransactionStoredEvent struct {
	// TransactionID contains the identifier of the stored Transaction.
	TransactionID utxo.TransactionID
}

// endregion ///////////////////////////////////////////////////////////////////////////////////////////////////////////

// region TransactionBookedEvent ///////////////////////////////////////////////////////////////////////////////////////

// TransactionBookedEvent is a container that acts as a dictionary for the TransactionBooked event related parameters.
type TransactionBookedEvent struct {
	// TransactionID contains the identifier of the booked Transaction.
	TransactionID utxo.TransactionID

	// Outputs contains the set of Outputs that this Transaction created.
	Outputs *utxo.Outputs

	// Context contains a Context provided by the caller that triggered this event.
	Context context.Context
}

// endregion ///////////////////////////////////////////////////////////////////////////////////////////////////////////

// region TransactionInclusionUpdatedEvent /////////////////////////////////////////////////////////////////////////////

// TransactionInclusionUpdatedEvent is a container that acts as a dictionary for the TransactionInclusionUpdated event
// related parameters.
type TransactionInclusionUpdatedEvent struct {
	// TransactionID contains the identifier of the booked Transaction.
	TransactionID utxo.TransactionID

	// TransactionMetadata contains the metadata of the Transaction.
	TransactionMetadata *TransactionMetadata

	// InclusionSlot contains the InclusionSlot after it was updated.
	InclusionSlot slot.Index

	// PreviousInclusionSlot contains the InclusionSlot before it was updated.
	PreviousInclusionSlot slot.Index
}

// endregion ///////////////////////////////////////////////////////////////////////////////////////////////////////////

// region TransactionForkedEvent ///////////////////////////////////////////////////////////////////////////////////////

// TransactionForkedEvent is a container that acts as a dictionary for the TransactionForked event related parameters.
type TransactionForkedEvent struct {
	// TransactionID contains the identifier of the forked Transaction.
	TransactionID utxo.TransactionID

	// ParentConflicts contains the set of ConflictIDs that form the parent Conflicts for the newly forked Transaction.
	ParentConflicts *advancedset.AdvancedSet[utxo.TransactionID]

	// Context contains a Context provided by the caller that triggered this event.
	Context context.Context
}

// endregion ///////////////////////////////////////////////////////////////////////////////////////////////////////////

// region TransactionConflictIDUpdatedEvent //////////////////////////////////////////////////////////////////////////////

// TransactionConflictIDUpdatedEvent is a container that acts as a dictionary for the TransactionConflictIDUpdated event
// related parameters.
type TransactionConflictIDUpdatedEvent struct {
	// TransactionID contains the identifier of the Transaction whose ConflictIDs were updated.
	TransactionID utxo.TransactionID

	// AddedConflictID contains the identifier of the Conflict that was added to the ConflictIDs of the Transaction.
	AddedConflictID utxo.TransactionID

	// RemovedConflictIDs contains the set of the ConflictIDs that were removed while updating the Transaction.
	RemovedConflictIDs *advancedset.AdvancedSet[utxo.TransactionID]

	// Context contains a Context provided by the caller that triggered this event.
	Context context.Context
}

// endregion ///////////////////////////////////////////////////////////////////////////////////////////////////////////

// region TransactionInvalidEvent //////////////////////////////////////////////////////////////////////////////////////

// TransactionInvalidEvent is a container that acts as a dictionary for the TransactionInvalid event related parameters.
type TransactionInvalidEvent struct {
	// TransactionID contains the identifier of the Transaction that was found to be invalid.
	TransactionID utxo.TransactionID

	// Reason contains the error that caused the Transaction to be considered invalid.
	Reason error

	// Context contains a Context provided by the caller that triggered this event.
	Context context.Context
}

// endregion ///////////////////////////////////////////////////////////////////////////////////////////////////////////

type TransactionEvent struct {
	Metadata       *TransactionMetadata
	CreatedOutputs []*OutputWithMetadata
	SpentOutputs   []*OutputWithMetadata
}
