package ping

const (
	MARSHALED_PACKET_HEADER = 0x00

	MARSHALED_PACKET_HEADER_START = 0
	MARSHALED_PACKET_HEADER_SIZE  = 1
	MARSHALED_PACKET_HEADER_END   = MARSHALED_PACKET_HEADER_START + MARSHALED_PACKET_HEADER_SIZE

	MARSHALED_TOTAL_SIZE = MARSHALED_PACKET_HEADER_END
)
