package ping

const (
	MARSHALLED_PACKET_HEADER = 0x00

	MARSHALLED_PACKET_HEADER_START = 0
	MARSHALLED_PACKET_HEADER_SIZE  = 1
	MARSHALLED_PACKET_HEADER_END   = MARSHALLED_PACKET_HEADER_START + MARSHALLED_PACKET_HEADER_SIZE

	MARSHALLED_TOTAL_SIZE = MARSHALLED_PACKET_HEADER_END
)
