---
## This playbook sets up the whole environment stack from scratch.

- hosts: metrics
  gather_facts: no
  vars:
    removeData: yes
  roles:
    - metrics

- hosts: supports
  gather_facts: no
  roles:
    - role: goshimmer-node
      nodeType: entrynode

- hosts: goshimmers:&internal_nodes
  gather_facts: no
  vars:
    nodeType: goshimmer
  roles:
    - goshimmer-node

- hosts: goshimmers:&public_nodes
  gather_facts: no
  vars:
    nodeType: public-node
  roles:
    - goshimmer-node

- hosts: vanilla-01*
  gather_facts: no
  roles:
    - snapshotter

- hosts: asset_registries
  gather_facts: no
  roles:
    - asset-registry

- hosts: lbs
  gather_facts: no
  roles:
    - lb
