---
## This playbook sets up the whole environment stack from scratch.

- hosts: metrics
  vars:
    removeData: yes
  roles:
    - metrics

- hosts: supports
  roles:
    - role: goshimmer-node
      nodeType: entrynode
    - role: goshimmer-node
      nodeType: analysis-server

- hosts: goshimmers:&internal_nodes
  vars:
    nodeType: goshimmer
  roles:
    - goshimmer-node

- hosts: goshimmers:&public_nodes
  vars:
    nodeType: public-node
  roles:
    - goshimmer-node

- hosts: vanilla-01*
  roles:
    - snapshotter

- hosts: asset_registries
  roles:
    - asset-registry

- hosts: lbs
  roles:
    - lb
