package identity

import "golang.org/x/crypto/ed25519"

const (
	IDENTIFIER_BYTE_LENGTH = 20
	PUBLIC_KEY_BYTE_LENGTH = ed25519.PublicKeySize
	SIGNATURE_BYTE_LENGTH  = ed25519.PublicKeySize + ed25519.SignatureSize

	MARSHALLED_IDENTITY_PUBLIC_KEY_START  = 0
	MARSHALLED_IDENTITY_PRIVATE_KEY_START = MARSHALLED_IDENTITY_PUBLIC_KEY_END

	MARSHALLED_IDENTITY_PUBLIC_KEY_SIZE  = PUBLIC_KEY_BYTE_LENGTH
	MARSHALLED_IDENTITY_PRIVATE_KEY_SIZE = ed25519.PrivateKeySize

	MARSHALLED_IDENTITY_PUBLIC_KEY_END  = MARSHALLED_IDENTITY_PUBLIC_KEY_START + MARSHALLED_IDENTITY_PUBLIC_KEY_SIZE
	MARSHALLED_IDENTITY_PRIVATE_KEY_END = MARSHALLED_IDENTITY_PRIVATE_KEY_START + MARSHALLED_IDENTITY_PRIVATE_KEY_SIZE

	MARSHALLED_IDENTITY_TOTAL_SIZE = MARSHALLED_IDENTITY_PRIVATE_KEY_END
)
