package identity

const (
	IDENTIFIER_BYTE_LENGTH = 20
	PUBLIC_KEY_BYTE_LENGTH = 65
	SIGNATURE_BYTE_LENGTH  = 65

	MARSHALLED_IDENTITY_PUBLIC_KEY_START  = 0
	MARSHALLED_IDENTITY_PRIVATE_KEY_START = MARSHALLED_IDENTITY_PUBLIC_KEY_END

	MARSHALLED_IDENTITY_PUBLIC_KEY_SIZE  = PUBLIC_KEY_BYTE_LENGTH
	MARSHALLED_IDENTITY_PRIVATE_KEY_SIZE = 32

	MARSHALLED_IDENTITY_PUBLIC_KEY_END  = MARSHALLED_IDENTITY_PUBLIC_KEY_START + MARSHALLED_IDENTITY_PUBLIC_KEY_SIZE
	MARSHALLED_IDENTITY_PRIVATE_KEY_END = MARSHALLED_IDENTITY_PRIVATE_KEY_START + MARSHALLED_IDENTITY_PRIVATE_KEY_SIZE

	MARSHALLED_IDENTITY_TOTAL_SIZE = MARSHALLED_IDENTITY_PRIVATE_KEY_END
)
