// Code generated by "stringer -type=ConnectionStatus"; DO NOT EDIT.

package manualpeering

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ConnStatusDisconnected-0]
	_ = x[ConnStatusConnected-1]
}

const _ConnectionStatus_name = "ConnStatusDisconnectedConnStatusConnected"

var _ConnectionStatus_index = [...]uint8{0, 22, 41}

func (i ConnectionStatus) String() string {
	if i < 0 || i >= ConnectionStatus(len(_ConnectionStatus_index)-1) {
		return "ConnectionStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ConnectionStatus_name[_ConnectionStatus_index[i]:_ConnectionStatus_index[i+1]]
}
