// Code generated by "stringer -type=connectionDirection"; DO NOT EDIT.

package manualpeering

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[connDirectionOutbound-0]
	_ = x[connDirectionInbound-1]
}

const _connectionDirection_name = "connDirectionOutboundconnDirectionInbound"

var _connectionDirection_index = [...]uint8{0, 21, 41}

func (i connectionDirection) String() string {
	if i < 0 || i >= connectionDirection(len(_connectionDirection_index)-1) {
		return "connectionDirection(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _connectionDirection_name[_connectionDirection_index[i]:_connectionDirection_index[i+1]]
}
