package connectnodes

import "crypto/sha256"

const (
	MARSHALED_PACKET_HEADER = 0x03

	MARSHALED_PACKET_HEADER_START = 0
	MARSHALED_PACKET_HEADER_SIZE  = 1
	MARSHALED_PACKET_HEADER_END   = MARSHALED_PACKET_HEADER_START + MARSHALED_PACKET_HEADER_SIZE

	MARSHALED_SOURCE_ID_START = MARSHALED_PACKET_HEADER_END
	MARSHALED_SOURCE_ID_SIZE  = sha256.Size
	MARSHALED_SOURCE_ID_END   = MARSHALED_SOURCE_ID_START + MARSHALED_SOURCE_ID_SIZE

	MARSHALED_TARGET_ID_START = MARSHALED_SOURCE_ID_END
	MARSHALED_TARGET_ID_SIZE  = sha256.Size
	MARSHALED_TARGET_ID_END   = MARSHALED_TARGET_ID_START + MARSHALED_TARGET_ID_SIZE

	MARSHALED_TOTAL_SIZE = MARSHALED_TARGET_ID_END
)
