run:
    tests: true

issues:
    exclude-use-default: false
    max-issues-per-linter: 0
    max-same-issues: 0
    exclude:
        - 'type name will be used as * by other packages, and that stutters; consider calling this *'
        - 'ifElseChain: rewrite if-else to switch statement'
        - "elseif: can replace 'else {if cond {}}' with 'else if cond {}'"
        - 'commentFormatting: put a space between `//` and comment text'
        - 'err113: do not define dynamic errors, use wrapped static errors instead: '
        - 'cyclomatic complexity * of func `*` is high'
    exclude-rules:
        -   path: _test\.go
            linters:
                - errcheck
                - bodyclose
                - noctx
                - dupl

linters-settings:
    govet:
        check-shadowing: true
    misspell:
        locale: US
    goimports:
        local-prefixes: github.com/iotaledger/goshimmer

linters:
    enable:
        - bodyclose
        - deadcode
        - dogsled
        #        - dupl
        #        - errcheck
        - gocritic
        - gocyclo
        - goerr113
        - gofumpt

        - misspell
        - goimports
        - govet
        - golint
    disable:
        - gochecknoglobals
        - errcheck
