# Documentation at http://goreleaser.com

# Project name
project_name: GoShimmer

# Environment variables
env:
  - GO111MODULE=on

# Builds
builds:
  - id: cli-wallet
    dir: ./tools/cli-wallet
    binary: cli-wallet
    goarch:
      - amd64
      - arm64

  - id: evil-spammer
    dir: ./tools/evil-spammer
    binary: evil-spammer
    goarch:
      - amd64
      - arm64

universal_binaries:
  - id : cli-wallet
    name_template: cli-wallet
    replace: true
  - id: evil-spammer
    name_template: evil-spammer
    replace: true

# Archives
archives:
  - id: cli-wallet
    builds:
      - cli-wallet
    name_template: >-
      {{ .Binary }}_{{ .Version }}_
      {{- if eq .Os "darwin"}}macOS
      {{- else }}{{ title .Os }}{{ end }}
      {{- if eq .Arch "amd64" }}_x86_64
      {{- else if eq .Arch "all" }}
      {{- else }}_{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE

  - id: evil-spammer
    builds:
      - evil-spammer
    name_template: >-
      {{ .Binary }}_{{ .Version }}_
      {{- if eq .Os "darwin"}}macOS
      {{- else }}{{ title .Os }}{{ end }}
      {{- if eq .Arch "amd64" }}_x86_64
      {{- else if eq .Arch "all" }}
      {{- else }}_{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE

# Checksum
checksum:
  name_template: "checksums.txt"

# Snapshot
snapshot:
  name_template: "{{ .Tag }}"

# Changelog
changelog:
  skip: true

# Release
release:
  prerelease: auto
  name_template: "{{.ProjectName}}-{{.Version}}"
  github:
    owner: iotaledger
    name: goshimmer
