package sybilprotection

import (
	"github.com/iotaledger/hive.go/core/generics/event"
	"github.com/iotaledger/hive.go/core/identity"
)

type Events struct {
	WeightUpdated *event.Linkable[*WeightUpdatedEvent]

	event.LinkableCollection[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.LinkableConstructor(func() (newEvents *Events) {
	return &Events{
		WeightUpdated: event.NewLinkable[*WeightUpdatedEvent](),
	}
})

type WeightUpdatedEvent struct {
	ID        identity.ID
	OldWeight *Weight
	NewWeight *Weight
}
