package sybilprotection

import (
	"github.com/iotaledger/hive.go/core/generics/event"
)

type Events struct {
	WeightsUpdated *event.Linkable[*WeightUpdates]

	event.LinkableCollection[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.LinkableConstructor(func() (newEvents *Events) {
	return &Events{
		WeightsUpdated: event.NewLinkable[*WeightUpdates](),
	}
})
