package chain

import (
	"github.com/iotaledger/hive.go/core/generics/event"
)

type Events struct {
	event.LinkableCollection[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.LinkableConstructor(func() (newEvents *Events) {
	return &Events{}
})
