package consensus

import (
	"github.com/iotaledger/hive.go/core/generics/event"

	"github.com/iotaledger/goshimmer/packages/protocol/chain/engine/consensus/acceptance"
)

type Events struct {
	Acceptance *acceptance.Events

	event.LinkableCollection[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.LinkableConstructor(func() (newEvents *Events) {
	return &Events{
		Acceptance: acceptance.NewEvents(),
	}
})
