package notarization

import (
	"github.com/iotaledger/goshimmer/packages/core/commitment"
	"github.com/iotaledger/goshimmer/packages/protocol/engine/ledger/mempool"
	"github.com/iotaledger/goshimmer/packages/protocol/engine/ledger/utxo"
	"github.com/iotaledger/goshimmer/packages/protocol/models"
	"github.com/iotaledger/hive.go/ads"
	"github.com/iotaledger/hive.go/runtime/event"
)

// Events is a container that acts as a dictionary for the events of the notarization manager.
type Events struct {
	SlotCommitted        *event.Event1[*SlotCommittedDetails]
	AcceptedBlockRemoved *event.Event1[models.BlockID]
	Error                *event.Event1[error]

	event.Group[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.CreateGroupConstructor(func() (self *Events) {
	return &Events{
		SlotCommitted:        event.New1[*SlotCommittedDetails](),
		AcceptedBlockRemoved: event.New1[models.BlockID](),
		Error:                event.New1[error](),
	}
})

type OutputsProvider func(callback func(*mempool.OutputWithMetadata) error) error

// SlotCommittedDetails contains the details of a committed slot.
type SlotCommittedDetails struct {
	Commitment            *commitment.Commitment
	AcceptedBlocks        *ads.Set[models.BlockID, *models.BlockID]
	AcceptedTransactions  *ads.Set[utxo.TransactionID, *utxo.TransactionID]
	SpentOutputs          OutputsProvider
	CreatedOutputs        OutputsProvider
	ActiveValidatorsCount int
}
