package ledgerstate

import (
	"crypto/rand"
	"fmt"
	"strconv"

	"github.com/iotaledger/goshimmer/packages/tangle/payload"
	"github.com/iotaledger/hive.go/byteutils"
	"github.com/iotaledger/hive.go/marshalutil"
	"github.com/iotaledger/hive.go/stringify"
	"github.com/mr-tron/base58"
	"golang.org/x/xerrors"
)

// region TransactionType //////////////////////////////////////////////////////////////////////////////////////////////

// TransactionType represents the Type of the Transaction in its role as a Payload.
var TransactionType = payload.NewType(1, "TransactionType", TransactionPayloadUnmarshaler)

// endregion ///////////////////////////////////////////////////////////////////////////////////////////////////////////

// region TransactionID ////////////////////////////////////////////////////////////////////////////////////////////////

// TransactionIDLength contains the amount of bytes that a marshaled version of the ID contains.
const TransactionIDLength = 32

// TransactionID is the type that represents the identifier of a Transaction.
type TransactionID [TransactionIDLength]byte

// GenesisTransactionID represents the genesis ID.
var GenesisTransactionID TransactionID

// TransactionIDFromBase58 creates a TransactionID from a base58 encoded string.
func TransactionIDFromBase58(base58String string) (id TransactionID, err error) {
	// decode string
	bytes, err := base58.Decode(base58String)
	if err != nil {
		err = xerrors.Errorf("failed to decode base58 encoded TransactionID (%v): %w", err, ErrBase58DecodeFailed)
		return
	}

	// sanitize input
	if len(bytes) != TransactionIDLength {
		err = fmt.Errorf("base58 decoded TransactionID '%s' does not match expected length of %d bytes", base58String, TransactionIDLength)
		return
	}

	// copy bytes to result
	copy(id[:], bytes)

	return
}

// TransactionIDFromBytes unmarshals a TransactionID from a sequence of bytes.
func TransactionIDFromBytes(bytes []byte) (result TransactionID, consumedBytes int, err error) {
	// parse the bytes
	marshalUtil := marshalutil.New(bytes)
	idBytes, idErr := marshalUtil.ReadBytes(TransactionIDLength)
	if idErr != nil {
		err = idErr

		return
	}
	copy(result[:], idBytes)
	consumedBytes = marshalUtil.ReadOffset()

	return
}

// TransactionIDFromMarshalUtil is a wrapper for simplified unmarshaling of TransactionIDs from a byte stream using the
// marshalUtil package.
func TransactionIDFromMarshalUtil(marshalUtil *marshalutil.MarshalUtil) (TransactionID, error) {
	id, err := marshalUtil.Parse(func(data []byte) (interface{}, int, error) { return TransactionIDFromBytes(data) })
	if err != nil {
		return TransactionID{}, err
	}

	return id.(TransactionID), nil
}

// RandomTransactionID creates a random TransactionID which can for example be used in unit tests.
func RandomTransactionID() (id TransactionID) {
	// generate a random sequence of bytes
	idBytes := make([]byte, TransactionIDLength)
	if _, err := rand.Read(idBytes); err != nil {
		panic(err)
	}

	// copy the generated bytes into the result
	copy(id[:], idBytes)

	return
}

// Bytes marshals the ID into a sequence of bytes.
func (i TransactionID) Bytes() []byte {
	return i[:]
}

// String creates a human readable base58 encoded version of the TransactionID.
func (i TransactionID) String() string {
	return base58.Encode(i[:])
}

// endregion ///////////////////////////////////////////////////////////////////////////////////////////////////////////

// region Transaction //////////////////////////////////////////////////////////////////////////////////////////////////

// Transaction represents a payload that is executing a value transfer in the ledger state.
type Transaction struct {
	essence      *TransactionEssence
	unlockBlocks UnlockBlocks
}

// TransactionPayloadUnmarshaler returns a Payload typed Transaction and is required for the payload Type definition.
func TransactionPayloadUnmarshaler(data []byte) (payload.Payload, error) {
	return TransactionFromMarshalUtil(marshalutil.New(data))
}

// TransactionFromMarshalUtil unmarshals a Transaction using a MarshalUtil (for easier unmarshaling).
func TransactionFromMarshalUtil(marshalUtil *marshalutil.MarshalUtil) (transaction *Transaction, err error) {
	readStartOffset := marshalUtil.ReadOffset()

	payloadSize, err := marshalUtil.ReadUint32()
	if err != nil {
		err = xerrors.Errorf("failed to parse payload size from MarshalUtil (%v): %w", err, ErrParseBytesFailed)
		return
	}
	payloadType, err := payload.TypeFromMarshalUtil(marshalUtil)
	if payloadType != TransactionType {
		err = xerrors.Errorf("payload type '%s' does not match expected '%s': %w", payloadType, TransactionType, ErrParseBytesFailed)
		return
	}

	transaction = &Transaction{}
	if transaction.essence, err = TransactionEssenceFromMarshalUtil(marshalUtil); err != nil {
		err = xerrors.Errorf("failed to parse TransactionEssence from MarshalUtil: %w", err)
		return
	}
	if transaction.unlockBlocks, err = UnlockBlocksFromMarshalUtil(marshalUtil); err != nil {
		err = xerrors.Errorf("failed to parse UnlockBlocks from MarshalUtil: %w", err)
		return
	}

	parsedBytes := marshalUtil.ReadOffset() - readStartOffset
	if parsedBytes != int(payloadSize) {
		err = xerrors.Errorf("parsed bytes (%d) did not match expected size (%d): %w", parsedBytes, payloadSize, ErrParseBytesFailed)
		return
	}

	return
}

// Type returns the Type of the Payload.
func (t *Transaction) Type() payload.Type {
	return TransactionType
}

func (t *Transaction) Essence() *TransactionEssence {
	return t.essence
}

func (t *Transaction) UnlockBlocks() UnlockBlocks {
	return t.unlockBlocks
}

// Bytes returns a marshaled version of the Transaction.
func (t *Transaction) Bytes() []byte {
	if t == nil {
		return marshalutil.New(marshalutil.UINT16_SIZE).WriteUint16(0).Bytes()
	}

	payloadBytes := byteutils.ConcatBytes(TransactionType.Bytes(), t.essence.Bytes(), t.unlockBlocks.Bytes())
	payloadBytesLength := len(payloadBytes)

	return marshalutil.New(marshalutil.UINT16_SIZE + payloadBytesLength).
		WriteUint16(uint16(payloadBytesLength)).
		WriteBytes(payloadBytes).
		Bytes()
}

// String returns a human readable version of the Transaction.
func (t *Transaction) String() string {
	return stringify.Struct("Transaction",
		stringify.StructField("essence", t.Essence()),
		stringify.StructField("unlockBlocks", t.UnlockBlocks()),
	)
}

// code contract (make sure the struct implements all required methods)
var _ payload.Payload = &Transaction{}

// endregion ///////////////////////////////////////////////////////////////////////////////////////////////////////////

// region TransactionEssence ///////////////////////////////////////////////////////////////////////////////////////////

type TransactionEssence struct {
	version TransactionEssenceVersion
	inputs  Inputs
	outputs Outputs
	payload payload.Payload
}

func TransactionEssenceFromMarshalUtil(marshalUtil *marshalutil.MarshalUtil) (transactionEssence *TransactionEssence, err error) {
	transactionEssence = &TransactionEssence{}
	if transactionEssence.version, err = TransactionEssenceVersionFromMarshalUtil(marshalUtil); err != nil {
		err = xerrors.Errorf("failed to parse TransactionEssenceVersion from MarshalUtil: %w", err)
		return
	}
	if transactionEssence.inputs, err = InputsFromMarshalUtil(marshalUtil); err != nil {
		err = xerrors.Errorf("failed to parse Inputs from MarshalUtil: %w", err)
		return
	}
	if transactionEssence.outputs, err = OutputsFromMarshalUtil(marshalUtil); err != nil {
		err = xerrors.Errorf("failed to parse Outputs from MarshalUtil: %w", err)
		return
	}
	if transactionEssence.payload, err = payload.FromMarshalUtil(marshalUtil); err != nil {
		err = xerrors.Errorf("failed to parse Payload from MarshalUtil: %w", err)
		return
	}

	return
}

// Bytes returns a marshaled version of the TransactionEssence.
func (t *TransactionEssence) Bytes() []byte {
	return marshalutil.New().
		Write(t.version).
		Write(t.inputs).
		Write(t.outputs).
		Write(t.payload).
		Bytes()
}

// endregion ///////////////////////////////////////////////////////////////////////////////////////////////////////////

// region TransactionEssenceVersion ////////////////////////////////////////////////////////////////////////////////////

// TransactionEssenceVersion represents a byte denoting a version augmented with some additional logic.
type TransactionEssenceVersion uint8

// OutputFromBytes unmarshals an Output from a sequence of bytes.
func TransactionEssenceVersionFromBytes(bytes []byte) (version TransactionEssenceVersion, consumedBytes int, err error) {
	marshalUtil := marshalutil.New(bytes)
	if version, err = TransactionEssenceVersionFromMarshalUtil(marshalUtil); err != nil {
		err = xerrors.Errorf("failed to parse version TransactionEssenceVersion from MarshalUtil: %w", err)
		return
	}
	consumedBytes = marshalUtil.ReadOffset()

	return
}

// TransactionEssenceVersionFromMarshalUtil unmarshals a TransactionEssenceVersion using a MarshalUtil (for easier
// unmarshaling).
func TransactionEssenceVersionFromMarshalUtil(marshalUtil *marshalutil.MarshalUtil) (version TransactionEssenceVersion, err error) {
	readByte, err := marshalUtil.ReadByte()
	if err != nil {
		err = xerrors.Errorf("failed to parse version TransactionEssenceVersion: %w", err)
		return
	}
	if readByte != 0 {
		err = xerrors.Errorf("failed to parse version TransactionEssenceVersion: %w", err)
		return
	}
	version = TransactionEssenceVersion(readByte)

	return
}

// Bytes returns a marshaled version of the TransactionEssenceVersion.
func (v TransactionEssenceVersion) Bytes() []byte {
	return []byte{byte(v)}
}

// Compare offers a comparator for TransactionEssenceVersions which returns -1 if otherInput is bigger, 1 if it is
// smaller and 0 if they are the same.
func (v TransactionEssenceVersion) Compare(other TransactionEssenceVersion) int {
	switch {
	case v < other:
		return -1
	case v > other:
		return 1
	default:
		return 0
	}
}

// String returns a human readable version of the TransactionEssenceVersion.
func (v TransactionEssenceVersion) String() string {
	return "TransactionEssenceVersion(" + strconv.Itoa(int(v)) + ")"
}

// endregion ///////////////////////////////////////////////////////////////////////////////////////////////////////////
