os: linux
language: go

go:
  - 1.13

cache:
  directories:
    - $HOME/gopath/pkg/mod

env:
  - GO111MODULE=on

# we are using go modules, so there is nothing to install
install: true

before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - golangci-lint run       # run a bunch of code checkers/linters in parallel
  - go test -v ./...
