{
 "title": "GoShimmer Global Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Autopeering", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Neighbor Count",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (nodeID) (global_nodes_neighbor_count)",
     "legendFormat": "{{nodeID}}"
    }
   ]
  },
  {
   "title": "Network Diameter",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "global_network_diameter" }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "info_cpu_usage", "legendFormat": "{{nodeID}}" }
   ]
  },
  {
   "title": "Memory Consumption",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "info_memory_usage_bytes/1024/1024",
     "legendFormat": "{{nodeID}}"
    }
   ]
  }
 ]
}