{
 "title": "Global Nodes View",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(iota_info_app, instance)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last commitmed epoch $instance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "repeat": "instance",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(last_commitment{}) by (epoch, instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last confirmed epoch $instance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
   "repeat": "instance",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(last_commitment{}) by (epoch, instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Epoch metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Epoch size metrics $instance",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "repeat": "instance",
   "targets": [
    {
     "expr": "epoch_counters{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocks removed per epoch",
   "type": "barchart",
   "description": "Orphaned blocks",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "repeat": "instance",
   "targets": [
    {
     "expr": "blk_removed_from_epoch{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Epoch Commitments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Commitments $instance",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "EI" } },
   "targets": [
    {
     "expr": "max(last_commitment{instance=\"$instance\", epoch!=\"0\"}) by (commitment, epoch)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of forks noticed by node",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "number_of_seen_other_commitments{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Missing commitments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Number of received missing commitments ",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "missing_commitments_received{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of missing commitments by node",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "missing_commitments_requested{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}