{
 "title": "GoShimmer Mana Research",
 "description": "Shows mana metrics with different EBM1 & EBM2 weights.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "NodeID",
    "label": "Node Identity",
    "query": "label_values(iota_info_app, nodeID)"
   }
  ]
 },
 "panels": [
  {
   "title": "Access Mana $NodeID",
   "type": "graph",
   "description": "Amount of access mana this node has.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mana_research_access{nodeID=\"$NodeID\",method=\"bm1\"}",
     "legendFormat": "Access Mana 1"
    },
    {
     "expr": "mana_research_access{nodeID=\"$NodeID\",method=\"bm2\"}",
     "legendFormat": "Access Mana 2"
    },
    {
     "expr": "mana_access{nodeID=\"$NodeID\"}",
     "legendFormat": "Access Mana Fifty-fifty"
    }
   ]
  },
  {
   "title": "Consensus Mana $NodeID",
   "type": "graph",
   "description": "Amount of consensus mana this node has.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mana_research_consensus{nodeID=\"$NodeID\",method=\"bm1\"}",
     "legendFormat": "Consensus Mana 1"
    },
    {
     "expr": "mana_research_consensus{nodeID=\"$NodeID\",method=\"bm2\"}",
     "legendFormat": "Consensus Mana 2"
    },
    {
     "expr": "mana_consensus{nodeID=\"$NodeID\"}",
     "legendFormat": "Consensus Mana Fifty-fifty"
    }
   ]
  },
  {
   "title": "Total Access Mana In Network",
   "type": "graph",
   "description": "Total Access  Mana In the network.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mana_access)",
     "legendFormat": "Total Access Mana Fifty-fifty In Network"
    },
    {
     "expr": "sum(mana_research_access{method=\"bm1\"})",
     "legendFormat": "Total Access Mana 1 In Network"
    },
    {
     "expr": "sum(mana_research_access{method=\"bm2\"})",
     "legendFormat": "Total Access Mana 2 In Network"
    }
   ]
  },
  {
   "title": "Total Consensus Mana In Network",
   "type": "graph",
   "description": "Total Consensus  Mana In the network.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mana_consensus)",
     "legendFormat": "Total Consensus Mana Fifty-fifty In Network"
    },
    {
     "expr": "sum(mana_research_consensus{method=\"bm1\"})",
     "legendFormat": "Total Consensus Mana 1 In Network"
    },
    {
     "expr": "sum(mana_research_consensus{method=\"bm2\"})",
     "legendFormat": "Total Consensus Mana 2 In Network"
    }
   ]
  },
  {
   "title": "Average Access Mana",
   "type": "graph",
   "description": "Average access mana of a node in the network.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(mana_research_access{method=\"bm1\"})",
     "legendFormat": "Access Mana 1"
    },
    {
     "expr": "avg(mana_research_access{method=\"bm2\"})",
     "legendFormat": "Access Mana 2"
    },
    { "expr": "avg(mana_access)", "legendFormat": "Access Mana Mixed" }
   ]
  },
  {
   "title": "Average Consensus Mana",
   "type": "graph",
   "description": "Average consensus mana of a node in the network.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(mana_research_consensus{method=\"bm1\"})",
     "legendFormat": "Consensus Mana 1"
    },
    {
     "expr": "avg(mana_research_consensus{method=\"bm2\"})",
     "legendFormat": "Consensus Mana 2"
    },
    { "expr": "avg(mana_consensus)", "legendFormat": "Consensus Mana Mixed" }
   ]
  },
  {
   "title": "Standard Deviation of Access Mana",
   "type": "graph",
   "description": "Standard deviation of access mana of nodes in the network.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stddev(mana_research_access{method=\"bm1\"})",
     "legendFormat": "Access Mana 1"
    },
    {
     "expr": "stddev(mana_research_access{method=\"bm2\"})",
     "legendFormat": "Access Mana 2"
    },
    { "expr": "stddev(mana_access)", "legendFormat": "Access Mana Mixed" }
   ]
  },
  {
   "title": "Standard Deviation of Consensus Mana",
   "type": "graph",
   "description": "Standard deviation of consensus mana of nodes in the network.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stddev(mana_research_consensus{method=\"bm1\"})",
     "legendFormat": "Consensus Mana 1"
    },
    {
     "expr": "stddev(mana_research_consensus{method=\"bm2\"})",
     "legendFormat": "Consensus Mana 2"
    },
    { "expr": "stddev(mana_consensus)", "legendFormat": "Consensus Mana Mixed" }
   ]
  },
  {
   "title": "Access Mana 1 Distribution In Network",
   "type": "graph",
   "description": "Histogram of access mana 1 of nodes by taking only EBM1 into account.",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Number of Nodes" }
   ],
   "targets": [
    {
     "expr": "mana_research_access{method=\"bm1\"}"
    }
   ]
  },
  {
   "title": "Access Mana Mixed Distribution In Network",
   "type": "graph",
   "description": "Histogram of access mana 2 of nodes by taking into account 50% EBM1 and 50% EBM2.",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Number of Nodes" }
   ],
   "targets": [
    { "expr": "mana_access" }
   ]
  },
  {
   "title": "Access Mana 2 Distribution In Network",
   "type": "graph",
   "description": "Histogram of access mana 2 of nodes by taking only EBM2 into account.",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Number of Nodes" }
   ],
   "targets": [
    {
     "expr": "mana_research_access{method=\"bm2\"}"
    }
   ]
  },
  {
   "title": "Consensus Mana 1 Distribution in Network",
   "type": "graph",
   "description": "Histogram of consensus mana 1 of nodes by only taking into account EBM1.",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Number of Nodes" }
   ],
   "targets": [
    {
     "expr": "mana_research_consensus{method=\"bm1\"}"
    }
   ]
  },
  {
   "title": "Consensus Mana Mixed Distribution in Network",
   "type": "graph",
   "description": "Histogram of consensus mana 2 of nodes by taking into account 50% EBM1 and 50% EBM2.",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Number of Nodes" }
   ],
   "targets": [
    { "expr": "mana_consensus" }
   ]
  },
  {
   "title": "Consensus Mana 2 Distribution in Network",
   "type": "graph",
   "description": "Histogram of consensus mana 2 of nodes by only taking into account EBM2.",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Number of Nodes" }
   ],
   "targets": [
    {
     "expr": "mana_research_consensus{method=\"bm2\"}"
    }
   ]
  },
  {
   "title": "Network Wide Access Mana 1",
   "type": "graph",
   "description": "Amount of access mana 1 of nodes in the network by taking only EBM1 into account.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mana_research_access{method=\"bm1\"}",
     "legendFormat": "{{nodeID}}"
    }
   ]
  },
  {
   "title": "Network Wide Access Mana Mixed",
   "type": "graph",
   "description": "Amount of access mana 2 of nodes in the network by taking into account 50% EBM1 and 50% EBM2.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mana_access", "legendFormat": "{{nodeID}}" }
   ]
  },
  {
   "title": "Network Wide Access Mana 2",
   "type": "graph",
   "description": "Amount of access mana 2 of nodes in the network by taking only EBM2 into account.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mana_research_access{method=\"bm2\"}",
     "legendFormat": "{{nodeID}}"
    }
   ]
  },
  {
   "title": "Access Mana 1 Allocation",
   "type": "grafana-piechart-panel",
   "description": "Allocation of access mana 1 of nodes in the network by taking only EBM1 into account.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "mana_research_access{method=\"bm1\"}",
     "legendFormat": "{{nodeID}}"
    }
   ]
  },
  {
   "title": "Access Mana Mixed Allocation",
   "type": "grafana-piechart-panel",
   "description": "Allocation of access mana 2 of nodes in the network by taking into account 50% EBM1 and 50% EBM2.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "mana_access", "legendFormat": "{{nodeID}}" }
   ]
  },
  {
   "title": "Access Mana 2 Allocation",
   "type": "grafana-piechart-panel",
   "description": "Allocation of access mana 2 of nodes in the network by taking only EBM2 into account.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "mana_research_access{method=\"bm2\"}",
     "legendFormat": "{{nodeID}}"
    }
   ]
  },
  {
   "title": "Network Wide Consensus Mana 1 ",
   "type": "graph",
   "description": "Amount of consensus mana of nodes in the network by taking only EBM1 into account.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mana_research_consensus{method=\"bm1\"}",
     "legendFormat": "{{nodeID}}"
    }
   ]
  },
  {
   "title": "Network Wide Consensus Mana Mixed",
   "type": "graph",
   "description": "Amount of consensus mana of nodes in the network by taking into account 50% EBM1 and 50% EBM2.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mana_consensus", "legendFormat": "{{nodeID}}" }
   ]
  },
  {
   "title": "Network Wide Consensus Mana 2",
   "type": "graph",
   "description": "Amount of consensus mana of nodes in the network by taking only EBM2 into account.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mana_research_consensus{method=\"bm2\"}",
     "legendFormat": "{{nodeID}}"
    }
   ]
  },
  {
   "title": "Consensus Mana 1 Allocation",
   "type": "grafana-piechart-panel",
   "description": "Allocation of consensus mana of nodes in the network by taking into account only EBM1.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "mana_research_consensus{method=\"bm1\"}",
     "legendFormat": "{{nodeID}}"
    }
   ]
  },
  {
   "title": "Consensus Mana Mixed Allocation",
   "type": "grafana-piechart-panel",
   "description": "Allocation of consensus mana of nodes in the network by taking into account 50% EBM1 and 50% EBM2.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "mana_consensus", "legendFormat": "{{nodeID}}" }
   ]
  },
  {
   "title": "Consensus Mana 2 Allocation",
   "type": "grafana-piechart-panel",
   "description": "Allocation of consensus mana of nodes in the network by taking into account only EBM2.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "mana_research_consensus{method=\"bm2\"}",
     "legendFormat": "{{nodeID}}"
    }
   ]
  },
  {
   "title": "Access Mana Percentile Development $NodeID",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "mana_access_percentile", "legendFormat": "Access Percentile Fifty-fifty" },
    {
     "expr": "mana_research_access_percentile{method=\"bm1\"}",
     "legendFormat": "Access Percentile 1"
    },
    {
     "expr": "mana_research_access_percentile{method=\"bm2\"}",
     "legendFormat": "Access Percentile 2"
    }
   ]
  },
  {
   "title": "Consensus Mana Percentile Development $NodeID",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 115 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "mana_consensus_percentile",
     "legendFormat": "Consensus Percentile Fifty-fifty"
    },
    {
     "expr": "mana_research_consensus_percentile{method=\"bm1\"}",
     "legendFormat": "Consensus Percentile 1"
    },
    {
     "expr": "mana_research_consensus_percentile{method=\"bm2\"}",
     "legendFormat": "Consensus Percentile 2"
    }
   ]
  }
 ]
}