package network

import (
	"github.com/iotaledger/hive.go/core/autopeering/peer"
	"github.com/iotaledger/hive.go/core/generics/event"

	"github.com/iotaledger/goshimmer/packages/protocol/engine/tangle/models"
)

type Events struct {
	BlockReceived *event.Linkable[*BlockReceivedEvent, Events, *Events]

	event.LinkableCollection[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.LinkableConstructor(func() (newEvents *Events) {
	return &Events{
		BlockReceived: event.NewLinkable[*BlockReceivedEvent, Events, *Events](),
	}
})

type BlockReceivedEvent struct {
	Block *models.Block
	Peer  *peer.Peer
}
