package epochgadget

import (
	"github.com/iotaledger/hive.go/runtime/event"

	"github.com/iotaledger/goshimmer/packages/core/epoch"
)

type Events struct {
	EpochConfirmed *event.Event1[epoch.Index]

	event.Group[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.CreateGroupConstructor(func() (newEvents *Events) {
	return &Events{
		EpochConfirmed: event.New1[epoch.Index](),
	}
})
