package epochgadget

import (
	"github.com/iotaledger/goshimmer/packages/core/epoch"
	"github.com/iotaledger/hive.go/core/generics/event"
)

type Events struct {
	EpochConfirmed *event.Linkable[epoch.Index]

	event.LinkableCollection[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.LinkableConstructor(func() (newEvents *Events) {
	return &Events{
		EpochConfirmed: event.NewLinkable[epoch.Index](),
	}
})
