{
 "title": "Global Nodes View",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(info_app, instance)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last commitmed epoch $instance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "repeat": "instance",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(commitments_latest{}) by (epoch, instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last confirmed epoch $instance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "repeat": "instance",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(commitments_latest{}) by (epoch, instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Epoch metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Accepted blocks per epoch $instance",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "repeat": "instance",
   "targets": [
    {
     "expr": "commitments_accepted_blocks{instance=\"$instance\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accepted transactions per epoch $instance",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "repeat": "instance",
   "targets": [
    {
     "expr": "commitments_accepted_transactions{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active validators per epoch $instance",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "repeat": "instance",
   "targets": [
    {
     "expr": "commitments_active_validators{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Epoch Commitments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Commitments $instance",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 71 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "EI" } },
   "targets": [
    {
     "expr": "max(commitments_latest{instance=\"$instance\", epoch!=\"0\"}) by (commitment, epoch)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of forks noticed by node",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 87 },
   "targets": [
    {
     "expr": "commitments_seen_total{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Missing commitments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "Number of received missing commitments ",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "commitments_missing_received_total{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of missing commitments by node",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 94 },
   "targets": [
    {
     "expr": "commitments_missing_requested_total{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}