package request

import (
	"github.com/iotaledger/goshimmer/packages/identity"
	"github.com/iotaledger/goshimmer/plugins/autopeering/types/peer"
)

const (
	MARSHALED_PACKET_HEADER = 0xBE

	PACKET_HEADER_START       = 0
	MARSHALED_ISSUER_START    = PACKET_HEADER_END
	MARSHALED_SIGNATURE_START = MARSHALED_ISSUER_END

	PACKET_HEADER_END       = PACKET_HEADER_START + PACKET_HEADER_SIZE
	MARSHALED_ISSUER_END    = MARSHALED_ISSUER_START + MARSHALED_ISSUER_SIZE
	MARSHALED_SIGNATURE_END = MARSHALED_SIGNATURE_START + MARSHALED_SIGNATURE_SIZE

	PACKET_HEADER_SIZE       = 1
	MARSHALED_ISSUER_SIZE    = peer.MARSHALED_TOTAL_SIZE
	MARSHALED_SIGNATURE_SIZE = identity.SIGNATURE_BYTE_LENGTH

	MARSHALED_TOTAL_SIZE = MARSHALED_SIGNATURE_END
)
