package request

import (
	"github.com/iotaledger/goshimmer/plugins/autopeering/types/peer"
)

const (
	PACKET_HEADER_SIZE = 1
	ISSUER_SIZE        = peer.MARSHALED_TOTAL_SIZE
	SIGNATURE_SIZE     = 65

	PACKET_HEADER_START = 0
	ISSUER_START        = PACKET_HEADER_END
	SIGNATURE_START     = ISSUER_END

	PACKET_HEADER_END = PACKET_HEADER_START + PACKET_HEADER_SIZE
	ISSUER_END        = ISSUER_START + ISSUER_SIZE
	SIGNATURE_END     = SIGNATURE_START + SIGNATURE_SIZE

	MARSHALED_TOTAL_SIZE = SIGNATURE_END

	MARSHALED_PACKET_HEADER = 0xBE
)
