package instance

import (
	"github.com/iotaledger/hive.go/core/generics/event"

	"github.com/iotaledger/goshimmer/packages/protocol/instance/clock"
	"github.com/iotaledger/goshimmer/packages/protocol/instance/engine"
	"github.com/iotaledger/goshimmer/packages/protocol/instance/tipmanager"
)

type Events struct {
	Engine     *engine.Events
	Clock      *clock.Events
	TipManager *tipmanager.Events

	event.LinkableCollection[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.LinkableConstructor(func() (newEvents *Events) {
	return &Events{
		Engine:     engine.NewEvents(),
		Clock:      clock.NewEvents(),
		TipManager: tipmanager.NewEvents(),
	}
})
