package protocol

import (
	"github.com/iotaledger/hive.go/core/generics/event"

	"github.com/iotaledger/goshimmer/packages/protocol/engine"
	"github.com/iotaledger/goshimmer/packages/protocol/engine/tangle/blockdag"
)

type Events struct {
	SwitchedEngine *event.LinkableCollectionEvent[*engine.Engine, Events, *Events]

	BlockDAG *blockdag.Events

	event.LinkableCollection[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.LinkableCollectionConstructor[Events](func(e *Events) {
	e.SwitchedEngine = event.NewLinkableCollectionEvent[*engine.Engine](e, func(target *Events) {
		e.SwitchedEngine.LinkTo(target.SwitchedEngine)
	})

	e.LinkTo(e)
})

func (e *Events) LinkToEngine(engine *engine.Engine) {
	if e.BlockDAG == nil {
		e.BlockDAG = blockdag.NewEvents(engine.Tangle.BlockDAG.Events)
	} else {
		e.BlockDAG.LinkTo(engine.Tangle.BlockDAG.Events)
	}

}
