// Code generated by protoc-gen-go. DO NOT EDIT.
// source: peer/proto/service.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TypePort_Type int32

const (
	TypePort_TCP TypePort_Type = 0
	TypePort_UDP TypePort_Type = 1
)

var TypePort_Type_name = map[int32]string{
	0: "TCP",
	1: "UDP",
}

var TypePort_Type_value = map[string]int32{
	"TCP": 0,
	"UDP": 1,
}

func (x TypePort_Type) String() string {
	return proto.EnumName(TypePort_Type_name, int32(x))
}

func (TypePort_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7271203e88dabbb0, []int{1, 0}
}

type ServiceMap struct {
	Map                  map[string]*TypePort `protobuf:"bytes,1,rep,name=map,proto3" json:"map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ServiceMap) Reset()         { *m = ServiceMap{} }
func (m *ServiceMap) String() string { return proto.CompactTextString(m) }
func (*ServiceMap) ProtoMessage()    {}
func (*ServiceMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_7271203e88dabbb0, []int{0}
}

func (m *ServiceMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceMap.Unmarshal(m, b)
}
func (m *ServiceMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceMap.Marshal(b, m, deterministic)
}
func (m *ServiceMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceMap.Merge(m, src)
}
func (m *ServiceMap) XXX_Size() int {
	return xxx_messageInfo_ServiceMap.Size(m)
}
func (m *ServiceMap) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceMap.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceMap proto.InternalMessageInfo

func (m *ServiceMap) GetMap() map[string]*TypePort {
	if m != nil {
		return m.Map
	}
	return nil
}

type TypePort struct {
	Type                 TypePort_Type `protobuf:"varint,1,opt,name=type,proto3,enum=proto.TypePort_Type" json:"type,omitempty"`
	Port                 int32         `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TypePort) Reset()         { *m = TypePort{} }
func (m *TypePort) String() string { return proto.CompactTextString(m) }
func (*TypePort) ProtoMessage()    {}
func (*TypePort) Descriptor() ([]byte, []int) {
	return fileDescriptor_7271203e88dabbb0, []int{1}
}

func (m *TypePort) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypePort.Unmarshal(m, b)
}
func (m *TypePort) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypePort.Marshal(b, m, deterministic)
}
func (m *TypePort) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypePort.Merge(m, src)
}
func (m *TypePort) XXX_Size() int {
	return xxx_messageInfo_TypePort.Size(m)
}
func (m *TypePort) XXX_DiscardUnknown() {
	xxx_messageInfo_TypePort.DiscardUnknown(m)
}

var xxx_messageInfo_TypePort proto.InternalMessageInfo

func (m *TypePort) GetType() TypePort_Type {
	if m != nil {
		return m.Type
	}
	return TypePort_TCP
}

func (m *TypePort) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func init() {
	proto.RegisterEnum("proto.TypePort_Type", TypePort_Type_name, TypePort_Type_value)
	proto.RegisterType((*ServiceMap)(nil), "proto.ServiceMap")
	proto.RegisterMapType((map[string]*TypePort)(nil), "proto.ServiceMap.MapEntry")
	proto.RegisterType((*TypePort)(nil), "proto.TypePort")
}

func init() { proto.RegisterFile("peer/proto/service.proto", fileDescriptor_7271203e88dabbb0) }

var fileDescriptor_7271203e88dabbb0 = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xcd, 0xda, 0xea, 0x7c, 0x03, 0x2d, 0xc1, 0x43, 0xd8, 0xa9, 0x14, 0x84, 0x20, 0xd2,
	0x40, 0xbd, 0x88, 0x47, 0x7f, 0xe0, 0x69, 0x50, 0xe2, 0xbc, 0x78, 0x4b, 0x4b, 0x98, 0xc5, 0x6e,
	0x09, 0x31, 0x9d, 0xf4, 0xec, 0x3f, 0x2e, 0x79, 0x75, 0x14, 0x76, 0x7a, 0x9f, 0xbc, 0xef, 0x27,
	0xdf, 0xc3, 0x03, 0x66, 0xb5, 0x76, 0xc2, 0x3a, 0xe3, 0x8d, 0xf8, 0xd6, 0x6e, 0xdf, 0x36, 0xba,
	0xc0, 0x17, 0x4d, 0x70, 0xe4, 0xbf, 0x04, 0xe0, 0x6d, 0x0c, 0x56, 0xca, 0xd2, 0x5b, 0x88, 0xb6,
	0xca, 0x32, 0x92, 0x45, 0x7c, 0x51, 0x2e, 0x47, 0xb5, 0x98, 0xf2, 0x62, 0xa5, 0xec, 0xcb, 0xce,
	0xbb, 0x41, 0x06, 0x6d, 0xf9, 0x0a, 0xf3, 0xc3, 0x82, 0xa6, 0x10, 0x7d, 0xe9, 0x81, 0x91, 0x8c,
	0xf0, 0x73, 0x19, 0x90, 0x5e, 0x43, 0xb2, 0x57, 0x5d, 0xaf, 0xd9, 0x2c, 0x23, 0x7c, 0x51, 0x5e,
	0xfe, 0xb7, 0xad, 0x07, 0xab, 0x2b, 0xe3, 0xbc, 0x1c, 0xd3, 0x87, 0xd9, 0x3d, 0xc9, 0x6b, 0x98,
	0x1f, 0xd6, 0x94, 0x43, 0xec, 0x07, 0xab, 0xb1, 0xe9, 0xa2, 0xbc, 0x3a, 0xfa, 0x85, 0x20, 0xd1,
	0xa0, 0x14, 0x62, 0x6b, 0x9c, 0xc7, 0xfe, 0x44, 0x22, 0xe7, 0x0c, 0xe2, 0x60, 0xd0, 0x33, 0x88,
	0xd6, 0x4f, 0x55, 0x7a, 0x12, 0xe0, 0xfd, 0xb9, 0x4a, 0xc9, 0xe3, 0xcd, 0x07, 0xdf, 0xb4, 0xfe,
	0xb3, 0xaf, 0x8b, 0xc6, 0x6c, 0xc5, 0x8f, 0xe9, 0x3a, 0xd5, 0x08, 0xd5, 0x7b, 0x13, 0x4e, 0xd4,
	0xee, 0x36, 0x62, 0x3a, 0x55, 0x7d, 0x8a, 0xe3, 0xee, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x5a, 0x51,
	0xeb, 0xaf, 0x3f, 0x01, 0x00, 0x00,
}
