package shutdown

const (
	ShutdownPriorityTangle = iota
	ShutdownPrioritySolidifier
	ShutdownPriorityBundleProcessor
	ShutdownPriorityAnalysis
	ShutdownPriorityMetrics
	ShutdownPriorityWebAPI
	ShutdownPriorityGossip
	ShutdownPriorityZMQ
	ShutdownPriorityAutopeering
	ShutdownPriorityGraph
	ShutdownPriorityUI
	ShutdownPriorityDashboard
	ShutdownPriorityTangleSpammer
	ShutdownPriorityStatusScreen
)
