package shutdown

const (
	ShutdownPriorityDatabase = iota
	ShutdownPriorityFPC
	ShutdownPriorityTangle
	ShutdownPriorityRemoteLog
	ShutdownPriorityAnalysis
	ShutdownPriorityMetrics
	ShutdownPriorityAutopeering
	ShutdownPriorityGossip
	ShutdownPriorityWebAPI
	ShutdownPriorityDashboard
	ShutdownPriorityGraph
	ShutdownPrioritySpammer
	ShutdownPriorityBadgerGarbageCollection
)
