package sequencetracker

import (
	"github.com/iotaledger/hive.go/core/generics/event"

	"github.com/iotaledger/goshimmer/packages/protocol/engine/tangle/booker/markers"
)

type Events struct {
	SequenceVotersUpdated *event.LinkableCollectionEvent[*SequenceVotersUpdatedEvent, Events, *Events]

	event.LinkableCollection[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.LinkableCollectionConstructor[Events](func(e *Events) {
	e.SequenceVotersUpdated = event.NewLinkableCollectionEvent[*SequenceVotersUpdatedEvent](e, func(target *Events) {
		e.SequenceVotersUpdated.LinkTo(target.SequenceVotersUpdated)
	})
})

type SequenceVotersUpdatedEvent struct {
	NewMaxSupportedIndex  markers.Index
	PrevMaxSupportedIndex markers.Index
	SequenceID            markers.SequenceID
}
