package salt

const (
	SALT_BYTES_LEN = 20

	MARSHALED_BYTES_START = 0
	MARSHALED_TIME_START  = MARSHALED_BYTES_END

	MARSHALED_BYTES_END = MARSHALED_BYTES_START + MARSHALED_BYTES_SIZE
	MARSHALED_TIME_END  = MARSHALED_TIME_START + MARSHALED_TIME_SIZE

	MARSHALED_BYTES_SIZE = SALT_BYTES_LEN
	MARSHALED_TIME_SIZE  = 15

	MARSHALED_TOTAL_SIZE = MARSHALED_TIME_END
)
