package salt

const (
	SALT_BYTES_LEN = 20

	MARSHALLED_BYTES_START = 0
	MARSHALLED_TIME_START  = MARSHALLED_BYTES_END

	MARSHALLED_BYTES_END = MARSHALLED_BYTES_START + MARSHALLED_BYTES_SIZE
	MARSHALLED_TIME_END  = MARSHALLED_TIME_START + MARSHALLED_TIME_SIZE

	MARSHALLED_BYTES_SIZE = SALT_BYTES_LEN
	MARSHALLED_TIME_SIZE  = 15

	MARSHALLED_TOTAL_SIZE = MARSHALLED_TIME_END
)
