package virtualvoting

import (
	"github.com/iotaledger/hive.go/core/generics/event"

	"github.com/iotaledger/goshimmer/packages/core/votes/conflicttracker"
	"github.com/iotaledger/goshimmer/packages/core/votes/sequencetracker"
	"github.com/iotaledger/goshimmer/packages/protocol/ledger/utxo"
)

type Events struct {
	BlockTracked *event.Linkable[*Block, Events, *Events]

	ConflictTracker *conflicttracker.Events[utxo.TransactionID]
	SequenceTracker *sequencetracker.Events

	event.LinkableCollection[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.NewLinkableEvents(func(self *Events) (linker func(*Events)) {
	self.BlockTracked = event.NewLinkable[*Block, Events]()
	self.ConflictTracker = conflicttracker.NewEvents[utxo.TransactionID]()
	self.SequenceTracker = sequencetracker.NewEvents()

	return func(newTarget *Events) {
		self.BlockTracked.LinkTo(newTarget.BlockTracked)
		self.ConflictTracker.LinkTo(newTarget.ConflictTracker)
		self.SequenceTracker.LinkTo(newTarget.SequenceTracker)
	}
})

func (e *Events) WithConflictTrackerEvents(events *conflicttracker.Events[utxo.TransactionID]) (self *Events) {
	e.ConflictTracker = events

	return e
}
