package virtualvoting

import (
	"github.com/iotaledger/hive.go/core/generics/event"

	"github.com/iotaledger/goshimmer/packages/core/votes/conflicttracker"
	"github.com/iotaledger/goshimmer/packages/core/votes/sequencetracker"
	"github.com/iotaledger/goshimmer/packages/protocol/ledger/utxo"
)

type Events struct {
	BlockTracked *event.Linkable[*Block, Events, *Events]

	ConflictTracker *conflicttracker.Events[utxo.TransactionID]
	SequenceTracker *sequencetracker.Events

	event.LinkableCollection[Events, *Events]
}

func linkCollection[T any](e *Events) {
	e.OnLinkUpdated(func(linkTarget *Events) {
		e.BlockTracked.LinkTo(linkTarget.BlockTracked)
	})
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.LinkableCollectionConstructor[Events](func(e *Events) {
	e.BlockTracked = event.Link(event.NewLinkable[*Block, Events](), e, func(target *Events) { e.BlockTracked.LinkTo(target.BlockTracked) })

	e.ConflictTracker = event.Link(conflicttracker.NewEvents[utxo.TransactionID](), e, func(target *Events) { e.ConflictTracker.LinkTo(target.ConflictTracker) })
	e.SequenceTracker = event.Link(sequencetracker.NewEvents(), e, func(target *Events) { e.SequenceTracker.LinkTo(target.SequenceTracker) })
})

func (e *Events) WithConflictTrackerEvents(events *conflicttracker.Events[utxo.TransactionID]) (self *Events) {
	e.ConflictTracker = events

	return e
}
