// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: packages/network/chain/proto/message.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Packet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Body:
	//
	//	*Packet_EpochCommitment
	//	*Packet_EpochCommitmentRequest
	//	*Packet_Negotiation
	Body isPacket_Body `protobuf_oneof:"body"`
}

func (x *Packet) Reset() {
	*x = Packet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packages_network_chain_proto_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_packages_network_chain_proto_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_packages_network_chain_proto_message_proto_rawDescGZIP(), []int{0}
}

func (m *Packet) GetBody() isPacket_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *Packet) GetEpochCommitment() *EpochCommitment {
	if x, ok := x.GetBody().(*Packet_EpochCommitment); ok {
		return x.EpochCommitment
	}
	return nil
}

func (x *Packet) GetEpochCommitmentRequest() *EpochCommitmentRequest {
	if x, ok := x.GetBody().(*Packet_EpochCommitmentRequest); ok {
		return x.EpochCommitmentRequest
	}
	return nil
}

func (x *Packet) GetNegotiation() *Negotiation {
	if x, ok := x.GetBody().(*Packet_Negotiation); ok {
		return x.Negotiation
	}
	return nil
}

type isPacket_Body interface {
	isPacket_Body()
}

type Packet_EpochCommitment struct {
	EpochCommitment *EpochCommitment `protobuf:"bytes,1,opt,name=epochCommitment,proto3,oneof"`
}

type Packet_EpochCommitmentRequest struct {
	EpochCommitmentRequest *EpochCommitmentRequest `protobuf:"bytes,2,opt,name=epochCommitmentRequest,proto3,oneof"`
}

type Packet_Negotiation struct {
	Negotiation *Negotiation `protobuf:"bytes,3,opt,name=negotiation,proto3,oneof"`
}

func (*Packet_EpochCommitment) isPacket_Body() {}

func (*Packet_EpochCommitmentRequest) isPacket_Body() {}

func (*Packet_Negotiation) isPacket_Body() {}

type EpochCommitment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bytes []byte `protobuf:"bytes,1,opt,name=Bytes,proto3" json:"Bytes,omitempty"`
}

func (x *EpochCommitment) Reset() {
	*x = EpochCommitment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packages_network_chain_proto_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EpochCommitment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpochCommitment) ProtoMessage() {}

func (x *EpochCommitment) ProtoReflect() protoreflect.Message {
	mi := &file_packages_network_chain_proto_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpochCommitment.ProtoReflect.Descriptor instead.
func (*EpochCommitment) Descriptor() ([]byte, []int) {
	return file_packages_network_chain_proto_message_proto_rawDescGZIP(), []int{1}
}

func (x *EpochCommitment) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

type EpochCommitmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bytes []byte `protobuf:"bytes,1,opt,name=Bytes,proto3" json:"Bytes,omitempty"`
}

func (x *EpochCommitmentRequest) Reset() {
	*x = EpochCommitmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packages_network_chain_proto_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EpochCommitmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpochCommitmentRequest) ProtoMessage() {}

func (x *EpochCommitmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_network_chain_proto_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpochCommitmentRequest.ProtoReflect.Descriptor instead.
func (*EpochCommitmentRequest) Descriptor() ([]byte, []int) {
	return file_packages_network_chain_proto_message_proto_rawDescGZIP(), []int{2}
}

func (x *EpochCommitmentRequest) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

type Negotiation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Negotiation) Reset() {
	*x = Negotiation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packages_network_chain_proto_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Negotiation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Negotiation) ProtoMessage() {}

func (x *Negotiation) ProtoReflect() protoreflect.Message {
	mi := &file_packages_network_chain_proto_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Negotiation.ProtoReflect.Descriptor instead.
func (*Negotiation) Descriptor() ([]byte, []int) {
	return file_packages_network_chain_proto_message_proto_rawDescGZIP(), []int{3}
}

var File_packages_network_chain_proto_message_proto protoreflect.FileDescriptor

var file_packages_network_chain_proto_message_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x2f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x63, 0x68,
	0x61, 0x69, 0x6e, 0x22, 0xe5, 0x01, 0x0a, 0x06, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x42,
	0x0a, 0x0f, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e,
	0x45, 0x70, 0x6f, 0x63, 0x68, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x48,
	0x00, 0x52, 0x0f, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x57, 0x0a, 0x16, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x43, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x45, 0x70, 0x6f, 0x63, 0x68,
	0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x48, 0x00, 0x52, 0x16, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x0b, 0x6e,
	0x65, 0x67, 0x6f, 0x74, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x4e, 0x65, 0x67, 0x6f, 0x74, 0x69, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0b, 0x6e, 0x65, 0x67, 0x6f, 0x74, 0x69, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x42, 0x06, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x27, 0x0a, 0x0f, 0x45,
	0x70, 0x6f, 0x63, 0x68, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x42,
	0x79, 0x74, 0x65, 0x73, 0x22, 0x2e, 0x0a, 0x16, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x43, 0x6f, 0x6d,
	0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x42,
	0x79, 0x74, 0x65, 0x73, 0x22, 0x0d, 0x0a, 0x0b, 0x4e, 0x65, 0x67, 0x6f, 0x74, 0x69, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x69, 0x6f, 0x74, 0x61, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2f, 0x67, 0x6f, 0x73,
	0x68, 0x69, 0x6d, 0x6d, 0x65, 0x72, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x2f,
	0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_packages_network_chain_proto_message_proto_rawDescOnce sync.Once
	file_packages_network_chain_proto_message_proto_rawDescData = file_packages_network_chain_proto_message_proto_rawDesc
)

func file_packages_network_chain_proto_message_proto_rawDescGZIP() []byte {
	file_packages_network_chain_proto_message_proto_rawDescOnce.Do(func() {
		file_packages_network_chain_proto_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_packages_network_chain_proto_message_proto_rawDescData)
	})
	return file_packages_network_chain_proto_message_proto_rawDescData
}

var file_packages_network_chain_proto_message_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_packages_network_chain_proto_message_proto_goTypes = []interface{}{
	(*Packet)(nil),                 // 0: chain.Packet
	(*EpochCommitment)(nil),        // 1: chain.EpochCommitment
	(*EpochCommitmentRequest)(nil), // 2: chain.EpochCommitmentRequest
	(*Negotiation)(nil),            // 3: chain.Negotiation
}
var file_packages_network_chain_proto_message_proto_depIdxs = []int32{
	1, // 0: chain.Packet.epochCommitment:type_name -> chain.EpochCommitment
	2, // 1: chain.Packet.epochCommitmentRequest:type_name -> chain.EpochCommitmentRequest
	3, // 2: chain.Packet.negotiation:type_name -> chain.Negotiation
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_packages_network_chain_proto_message_proto_init() }
func file_packages_network_chain_proto_message_proto_init() {
	if File_packages_network_chain_proto_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_packages_network_chain_proto_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Packet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packages_network_chain_proto_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EpochCommitment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packages_network_chain_proto_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EpochCommitmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packages_network_chain_proto_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Negotiation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_packages_network_chain_proto_message_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Packet_EpochCommitment)(nil),
		(*Packet_EpochCommitmentRequest)(nil),
		(*Packet_Negotiation)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_packages_network_chain_proto_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packages_network_chain_proto_message_proto_goTypes,
		DependencyIndexes: file_packages_network_chain_proto_message_proto_depIdxs,
		MessageInfos:      file_packages_network_chain_proto_message_proto_msgTypes,
	}.Build()
	File_packages_network_chain_proto_message_proto = out.File
	file_packages_network_chain_proto_message_proto_rawDesc = nil
	file_packages_network_chain_proto_message_proto_goTypes = nil
	file_packages_network_chain_proto_message_proto_depIdxs = nil
}
