// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/peering.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	proto1 "github.com/wollac/autopeering/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("grpc/peering.proto", fileDescriptor_55ee00b534dd8755) }

var fileDescriptor_55ee00b534dd8755 = []byte{
	// 120 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x4a, 0x2f, 0x2a, 0x48,
	0xd6, 0x2f, 0x48, 0x4d, 0x2d, 0xca, 0xcc, 0x4b, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0x01, 0x89, 0x49, 0x09, 0x81, 0x39, 0xfa, 0x05, 0x89, 0xc9, 0xd9, 0xa9, 0x25, 0x10, 0x19, 0x23,
	0x7d, 0x2e, 0xf6, 0x00, 0x88, 0x52, 0x21, 0x15, 0x2e, 0x96, 0x00, 0x10, 0xcd, 0x0b, 0x91, 0xd2,
	0x0b, 0x00, 0xab, 0x93, 0x42, 0xe5, 0x3a, 0xa9, 0x44, 0x29, 0xa5, 0x67, 0x96, 0x64, 0x94, 0x26,
	0xe9, 0x25, 0xe7, 0xe7, 0xea, 0x97, 0xe7, 0xe7, 0xe4, 0x24, 0x26, 0xeb, 0x27, 0x96, 0x96, 0xe4,
	0x43, 0x6d, 0xd4, 0x07, 0x59, 0x95, 0xc4, 0x06, 0xd6, 0x63, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff,
	0xa9, 0x6a, 0x99, 0x1f, 0x8d, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PeeringClient is the client API for Peering service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PeeringClient interface {
	Ping(ctx context.Context, in *proto1.Packet, opts ...grpc.CallOption) (*proto1.Packet, error)
}

type peeringClient struct {
	cc *grpc.ClientConn
}

func NewPeeringClient(cc *grpc.ClientConn) PeeringClient {
	return &peeringClient{cc}
}

func (c *peeringClient) Ping(ctx context.Context, in *proto1.Packet, opts ...grpc.CallOption) (*proto1.Packet, error) {
	out := new(proto1.Packet)
	err := c.cc.Invoke(ctx, "/grpc.Peering/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PeeringServer is the server API for Peering service.
type PeeringServer interface {
	Ping(context.Context, *proto1.Packet) (*proto1.Packet, error)
}

// UnimplementedPeeringServer can be embedded to have forward compatible implementations.
type UnimplementedPeeringServer struct {
}

func (*UnimplementedPeeringServer) Ping(ctx context.Context, req *proto1.Packet) (*proto1.Packet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}

func RegisterPeeringServer(s *grpc.Server, srv PeeringServer) {
	s.RegisterService(&_Peering_serviceDesc, srv)
}

func _Peering_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto1.Packet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeeringServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Peering/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeeringServer).Ping(ctx, req.(*proto1.Packet))
	}
	return interceptor(ctx, in, info, handler)
}

var _Peering_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Peering",
	HandlerType: (*PeeringServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Peering_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/peering.proto",
}
