- name: Create node directory
  file:
    path: /opt/{{ nodeType }}
    state: directory
    mode: '0755'

- name: Template docker-compose.yml
  template:
    src: docker-compose-{{ nodeType }}.yml.j2
    dest: /opt/{{ nodeType }}/docker-compose.yml
    mode: '0644'

- name: Stop existing services gracefully
  community.general.docker_compose:
    project_src: /opt/{{ nodeType }}
    timeout: 180
    state: present
    stopped: yes

- name: Tear down existing services
  community.general.docker_compose:
    project_src: /opt/{{ nodeType }}
    state: absent

- name: Create enrtynode db directory
  file:
    path: /opt/{{ nodeType }}/db
    state: directory
    mode: '0777'

- name: Remove DB
  shell:
    cmd: rm -rf /opt/{{ nodeType }}/db/*
    warn: false

- name: Clean conntrack
  shell:
    cmd: conntrack -D -p udp
    warn: false
  ignore_errors: true # sometimes conntrack might not be installed

- name: Run node
  community.general.docker_compose:
    project_src: /opt/{{ nodeType }}
    timeout: 180
    state: present
    pull: yes
