- name: Pull docker image async
  shell: docker pull "{{ goshimmerDockerImage }}:{{ goshimmerDockerTag }}"
  async: 300
  poll: 5

- name: Create node directory
  file:
    path: /opt/{{ nodeType }}
    state: directory
    mode: '0755'

- name: Template docker-compose.yml
  template:
    src: docker-compose-{{ nodeType }}.yml.j2
    dest: /opt/{{ nodeType }}/docker-compose.yml
    mode: '0644'

- name: Stop existing services gracefully
  community.general.docker_compose:
    project_src: /opt/{{ nodeType }}
    timeout: 180
    state: present
    stopped: yes

- name: Tear down existing services
  community.general.docker_compose:
    project_src: /opt/{{ nodeType }}
    state: absent

- name: Create DB directory
  file:
    path: /opt/{{ nodeType }}/db
    state: directory
    mode: '0777'

- name: Create Retainer directory
  file:
    path: /opt/{{ nodeType }}/retainer
    state: directory
    mode: '0777'


- name: Remove DB
  shell:
    cmd: rm -rf /opt/{{ nodeType }}/db/*

- name: Remove Retainer contents
  shell:
    cmd: rm -rf /opt/{{ nodeType }}/retainer/*

- name: Clean conntrack
  shell:
    cmd: conntrack -D -p udp
  ignore_errors: true # sometimes conntrack might not be installed

- name: Run node
  community.general.docker_compose:
    project_src: /opt/{{ nodeType }}
    timeout: 180
    state: present
    pull: yes

- name: Create prof directory
  file:
    path: /opt/pprof
    state: directory
    mode: '0777'

- name: Remove pprof contents
  shell:
    cmd: rm -rf /opt/pprof/*

- name: Cronjob for pprof dumps every minute
  ansible.builtin.cron:
    name: "dump pprof profile"
    minute: "*"
    job: "docker run -v /opt/pprof/:/root/pprof/ --add-host host.docker.internal:host-gateway --rm golang:1.19-bullseye go tool pprof -proto \"host.docker.internal:6061/debug/pprof/heap\""

- name: Cronjob to clean old pprof dumps
  ansible.builtin.cron:
    name: "clean old pprof dumps"
    minute: "*"
    job: "(cd /opt/pprof/ && ls -tp | grep -v '/$' | tail -n +120 | xargs -I {} rm -- {})"
