package event

import (
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/iotaledger/goshimmer/packages/protocol/models"
)

func Benchmark(b *testing.B) {
	testEvent := New1[int]()
	testEvent.Hook(func(int) {})
	testEvent.Hook(func(int) {})
	testEvent.Hook(func(int) {})
	testEvent.Hook(func(int) {})

	b.ResetTimer()

	for i := 0; i < b.N; i++ {
		testEvent.Trigger(i)
	}
}

func TestLink(t *testing.T) {
	sourceEvents := NewEvents()

	eventTriggered := 0
	linkedEvents := NewEvents(sourceEvents)
	linkedEvents.BlockIssued.Hook(func(block *models.Block) {
		eventTriggered++
	})

	sourceEvents.BlockIssued.Trigger(&models.Block{})
	require.Equal(t, eventTriggered, 1)

	linkedEvents.LinkTo(nil)

	sourceEvents.BlockIssued.Trigger(&models.Block{})
	require.Equal(t, eventTriggered, 1)

	linkedEvents.LinkTo(sourceEvents)

	sourceEvents.BlockIssued.Trigger(&models.Block{})
	require.Equal(t, eventTriggered, 2)
}

// Events represents events happening on a block factory.
type Events struct {
	// Triggered when a block is issued, i.e. sent to the protocol to be processed.
	BlockIssued *Event1[*models.Block]

	// Fired when an error occurred.
	Error *Event1[error]

	Group[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = NewGroup(func() *Events {
	return &Events{
		BlockIssued: New1[*models.Block](),
		Error:       New1[error](),
	}
})
