// Code generated by protoc-gen-go. DO NOT EDIT.
// source: discover/proto/message.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	proto1 "github.com/iotaledger/autopeering-sim/peer/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Ping struct {
	// protocol version number
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// string form of the return address (e.g. "192.0.2.1:25", "[2001:db8::1]:80")
	From string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	// string form of the recipient address
	To string `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	// unix time
	Timestamp            int64    `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f14146485f66eb, []int{0}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Ping) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Ping) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Ping) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type Pong struct {
	// hash of the ping packet
	PingHash []byte `protobuf:"bytes,1,opt,name=ping_hash,json=pingHash,proto3" json:"ping_hash,omitempty"`
	// string form of the recipient address
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f14146485f66eb, []int{1}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetPingHash() []byte {
	if m != nil {
		return m.PingHash
	}
	return nil
}

func (m *Pong) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

type DiscoveryRequest struct {
	// string form of the recipient address
	To string `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	// unix time
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscoveryRequest) Reset()         { *m = DiscoveryRequest{} }
func (m *DiscoveryRequest) String() string { return proto.CompactTextString(m) }
func (*DiscoveryRequest) ProtoMessage()    {}
func (*DiscoveryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f14146485f66eb, []int{2}
}

func (m *DiscoveryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscoveryRequest.Unmarshal(m, b)
}
func (m *DiscoveryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscoveryRequest.Marshal(b, m, deterministic)
}
func (m *DiscoveryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscoveryRequest.Merge(m, src)
}
func (m *DiscoveryRequest) XXX_Size() int {
	return xxx_messageInfo_DiscoveryRequest.Size(m)
}
func (m *DiscoveryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscoveryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DiscoveryRequest proto.InternalMessageInfo

func (m *DiscoveryRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *DiscoveryRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type DiscoveryResponse struct {
	// hash of the corresponding request
	ReqHash []byte `protobuf:"bytes,1,opt,name=req_hash,json=reqHash,proto3" json:"req_hash,omitempty"`
	// list of peers
	Peers                []*proto1.Peer `protobuf:"bytes,2,rep,name=peers,proto3" json:"peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DiscoveryResponse) Reset()         { *m = DiscoveryResponse{} }
func (m *DiscoveryResponse) String() string { return proto.CompactTextString(m) }
func (*DiscoveryResponse) ProtoMessage()    {}
func (*DiscoveryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f14146485f66eb, []int{3}
}

func (m *DiscoveryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscoveryResponse.Unmarshal(m, b)
}
func (m *DiscoveryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscoveryResponse.Marshal(b, m, deterministic)
}
func (m *DiscoveryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscoveryResponse.Merge(m, src)
}
func (m *DiscoveryResponse) XXX_Size() int {
	return xxx_messageInfo_DiscoveryResponse.Size(m)
}
func (m *DiscoveryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscoveryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DiscoveryResponse proto.InternalMessageInfo

func (m *DiscoveryResponse) GetReqHash() []byte {
	if m != nil {
		return m.ReqHash
	}
	return nil
}

func (m *DiscoveryResponse) GetPeers() []*proto1.Peer {
	if m != nil {
		return m.Peers
	}
	return nil
}

func init() {
	proto.RegisterType((*Ping)(nil), "proto.Ping")
	proto.RegisterType((*Pong)(nil), "proto.Pong")
	proto.RegisterType((*DiscoveryRequest)(nil), "proto.DiscoveryRequest")
	proto.RegisterType((*DiscoveryResponse)(nil), "proto.DiscoveryResponse")
}

func init() { proto.RegisterFile("discover/proto/message.proto", fileDescriptor_43f14146485f66eb) }

var fileDescriptor_43f14146485f66eb = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x91, 0xbf, 0x4f, 0xfb, 0x30,
	0x10, 0xc5, 0x95, 0x1f, 0xfd, 0xb6, 0xb9, 0x7e, 0x41, 0x60, 0x09, 0x29, 0x40, 0x07, 0xc8, 0xd4,
	0x85, 0x44, 0xa2, 0x88, 0x19, 0x21, 0x06, 0xc6, 0xe2, 0x91, 0x05, 0x39, 0xad, 0x49, 0x2c, 0xe1,
	0x9c, 0x1b, 0x3b, 0x48, 0xfc, 0xf7, 0x5c, 0x9c, 0x16, 0x0a, 0x03, 0x93, 0xef, 0x3d, 0x5b, 0xef,
	0x73, 0x77, 0x86, 0xd9, 0x5a, 0xd9, 0x15, 0xbe, 0xcb, 0xb6, 0x30, 0x2d, 0x3a, 0x2c, 0xb4, 0xb4,
	0x56, 0x54, 0x32, 0xf7, 0x8a, 0x8d, 0xfc, 0x71, 0x76, 0x62, 0xe4, 0xd7, 0x83, 0xbe, 0x1c, 0x6e,
	0xb3, 0x12, 0xe2, 0xa5, 0x6a, 0x2a, 0x96, 0xc2, 0x98, 0x02, 0xac, 0xc2, 0x26, 0x0d, 0x2e, 0x82,
	0xf9, 0x01, 0xdf, 0x49, 0xc6, 0x20, 0x7e, 0x6d, 0x51, 0xa7, 0x21, 0xd9, 0x09, 0xf7, 0x35, 0x3b,
	0x84, 0xd0, 0x61, 0x1a, 0x79, 0x87, 0x2a, 0x36, 0x83, 0xc4, 0x29, 0xc2, 0x3a, 0xa1, 0x4d, 0x1a,
	0x93, 0x1d, 0xf1, 0x6f, 0x23, 0x5b, 0x10, 0x03, 0x89, 0x71, 0x0e, 0x89, 0x21, 0xd6, 0x4b, 0x2d,
	0x6c, 0xed, 0x29, 0xff, 0xf9, 0xa4, 0x37, 0x1e, 0x49, 0x6f, 0x23, 0xc3, 0x5d, 0x64, 0x76, 0x07,
	0x47, 0x0f, 0xdb, 0xb1, 0x3e, 0xb8, 0xdc, 0x74, 0x94, 0xf5, 0x37, 0x36, 0xf8, 0x8d, 0x7d, 0x82,
	0xe3, 0xbd, 0x04, 0x6b, 0xb0, 0xb1, 0x92, 0x9d, 0xc2, 0xa4, 0x95, 0x9b, 0xfd, 0x16, 0xc6, 0xa4,
	0x7d, 0x07, 0x97, 0x30, 0xea, 0x17, 0x63, 0xa9, 0x89, 0x68, 0x3e, 0xbd, 0x9e, 0x0e, 0x1b, 0xca,
	0x97, 0xe4, 0xf1, 0xe1, 0xe6, 0xfe, 0xf6, 0xf9, 0xa6, 0x52, 0xae, 0xee, 0xca, 0x7c, 0x85, 0xba,
	0x50, 0xe8, 0xc4, 0x9b, 0x5c, 0x57, 0xb4, 0x57, 0xd1, 0x39, 0xec, 0x9f, 0xd0, 0x34, 0x57, 0x56,
	0xe9, 0xe2, 0xe7, 0x8f, 0x94, 0xff, 0xfc, 0xb1, 0xf8, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x70, 0x1b,
	0xfa, 0xbd, 0xaa, 0x01, 0x00, 0x00,
}
