package salt

const (
    SALT_BYTES_SIZE = 20
    SALT_TIME_SIZE  = 15

    SALT_BYTES_START = 0
    SALT_TIME_START  = SALT_BYTES_END

    SALT_BYTES_END = SALT_BYTES_START + SALT_BYTES_SIZE
    SALT_TIME_END  = SALT_TIME_START + SALT_TIME_SIZE

    SALT_MARSHALLED_SIZE = SALT_TIME_END
)
