package approvers

const (
	MARSHALED_APPROVERS_HASHES_COUNT_START = 0
	MARSHALED_APPROVERS_HASH_START         = MARSHALED_APPROVERS_HASHES_COUNT_END
	MARSHALED_APPROVERS_HASHES_START       = MARSHALED_APPROVERS_HASH_END

	MARSHALED_APPROVERS_HASHES_COUNT_END = MARSHALED_APPROVERS_HASHES_COUNT_START + MARSHALED_APPROVERS_HASHES_COUNT_SIZE
	MARSHALED_APPROVERS_HASH_END         = MARSHALED_APPROVERS_HASH_START + MARSHALED_APPROVERS_HASH_SIZE

	MARSHALED_APPROVERS_HASHES_COUNT_SIZE = 8
	MARSHALED_APPROVERS_HASH_SIZE         = 81
	MARSHALED_APPROVERS_MIN_SIZE          = MARSHALED_APPROVERS_HASHES_COUNT_SIZE + MARSHALED_APPROVERS_HASH_SIZE
)
