package congestioncontrol

import (
	"github.com/iotaledger/hive.go/core/generics/event"

	"github.com/iotaledger/goshimmer/packages/protocol/instance/congestioncontrol/icca/mana"
	"github.com/iotaledger/goshimmer/packages/protocol/instance/congestioncontrol/icca/scheduler"
)

type Events struct {
	Scheduler *scheduler.Events
	Tracker   *mana.Events

	event.LinkableCollection[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.LinkableConstructor(func() (newEvents *Events) {
	return &Events{
		Scheduler: scheduler.NewEvents(),
		Tracker:   mana.NewEvents(),
	}
})
