package eventticker

import (
	"github.com/iotaledger/goshimmer/packages/core/epoch"
	"github.com/iotaledger/hive.go/runtime/event"
)

// Events represents events happening on a EventTicker.
type Events[T epoch.IndexedID] struct {
	// Request is an event that is triggered when the requester wants to request the given entity.
	Tick *event.Event1[T]

	// RequestQueued is an event that is triggered when a new request is started.
	TickerStarted *event.Event1[T]

	// RequestStopped is an event that is triggered when a request is stopped.
	TickerStopped *event.Event1[T]

	// RequestFailed is an event that is triggered when a request is stopped after too many attempts.
	TickerFailed *event.Event1[T]

	event.Group[Events[T], *Events[T]]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
func NewEvents[T epoch.IndexedID](linkedEvents ...*Events[T]) (newEvents *Events[T]) {
	return event.CreateGroupConstructor(func() *Events[T] {
		return &Events[T]{
			Tick:          event.New1[T](),
			TickerStarted: event.New1[T](),
			TickerStopped: event.New1[T](),
			TickerFailed:  event.New1[T](),
		}
	})(linkedEvents...)
}
