// Code generated by protoc-gen-go. DO NOT EDIT.
// source: selection/proto/message.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	proto2 "github.com/iotaledger/autopeering-sim/peer/proto"
	proto1 "github.com/iotaledger/autopeering-sim/salt/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PeeringRequest struct {
	// string form of the recipient address
	To string `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	// unix time
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// salt of the requester
	Salt *proto1.Salt `protobuf:"bytes,3,opt,name=salt,proto3" json:"salt,omitempty"`
	// services supported by the requester
	Services             *proto2.ServiceMap `protobuf:"bytes,4,opt,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *PeeringRequest) Reset()         { *m = PeeringRequest{} }
func (m *PeeringRequest) String() string { return proto.CompactTextString(m) }
func (*PeeringRequest) ProtoMessage()    {}
func (*PeeringRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e39e4329bafd72d5, []int{0}
}

func (m *PeeringRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeeringRequest.Unmarshal(m, b)
}
func (m *PeeringRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeeringRequest.Marshal(b, m, deterministic)
}
func (m *PeeringRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeeringRequest.Merge(m, src)
}
func (m *PeeringRequest) XXX_Size() int {
	return xxx_messageInfo_PeeringRequest.Size(m)
}
func (m *PeeringRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PeeringRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PeeringRequest proto.InternalMessageInfo

func (m *PeeringRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *PeeringRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *PeeringRequest) GetSalt() *proto1.Salt {
	if m != nil {
		return m.Salt
	}
	return nil
}

func (m *PeeringRequest) GetServices() *proto2.ServiceMap {
	if m != nil {
		return m.Services
	}
	return nil
}

type PeeringResponse struct {
	// hash of the corresponding request
	ReqHash []byte `protobuf:"bytes,1,opt,name=req_hash,json=reqHash,proto3" json:"req_hash,omitempty"`
	// response of a peering request
	Status bool `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	// services supported by the responding peer
	Services             *proto2.ServiceMap `protobuf:"bytes,3,opt,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *PeeringResponse) Reset()         { *m = PeeringResponse{} }
func (m *PeeringResponse) String() string { return proto.CompactTextString(m) }
func (*PeeringResponse) ProtoMessage()    {}
func (*PeeringResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e39e4329bafd72d5, []int{1}
}

func (m *PeeringResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeeringResponse.Unmarshal(m, b)
}
func (m *PeeringResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeeringResponse.Marshal(b, m, deterministic)
}
func (m *PeeringResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeeringResponse.Merge(m, src)
}
func (m *PeeringResponse) XXX_Size() int {
	return xxx_messageInfo_PeeringResponse.Size(m)
}
func (m *PeeringResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PeeringResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PeeringResponse proto.InternalMessageInfo

func (m *PeeringResponse) GetReqHash() []byte {
	if m != nil {
		return m.ReqHash
	}
	return nil
}

func (m *PeeringResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *PeeringResponse) GetServices() *proto2.ServiceMap {
	if m != nil {
		return m.Services
	}
	return nil
}

type PeeringDrop struct {
	// string form of the recipient address
	To string `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	// unix time
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeeringDrop) Reset()         { *m = PeeringDrop{} }
func (m *PeeringDrop) String() string { return proto.CompactTextString(m) }
func (*PeeringDrop) ProtoMessage()    {}
func (*PeeringDrop) Descriptor() ([]byte, []int) {
	return fileDescriptor_e39e4329bafd72d5, []int{2}
}

func (m *PeeringDrop) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeeringDrop.Unmarshal(m, b)
}
func (m *PeeringDrop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeeringDrop.Marshal(b, m, deterministic)
}
func (m *PeeringDrop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeeringDrop.Merge(m, src)
}
func (m *PeeringDrop) XXX_Size() int {
	return xxx_messageInfo_PeeringDrop.Size(m)
}
func (m *PeeringDrop) XXX_DiscardUnknown() {
	xxx_messageInfo_PeeringDrop.DiscardUnknown(m)
}

var xxx_messageInfo_PeeringDrop proto.InternalMessageInfo

func (m *PeeringDrop) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *PeeringDrop) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*PeeringRequest)(nil), "proto.PeeringRequest")
	proto.RegisterType((*PeeringResponse)(nil), "proto.PeeringResponse")
	proto.RegisterType((*PeeringDrop)(nil), "proto.PeeringDrop")
}

func init() { proto.RegisterFile("selection/proto/message.proto", fileDescriptor_e39e4329bafd72d5) }

var fileDescriptor_e39e4329bafd72d5 = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x51, 0x4f, 0x4b, 0xfb, 0x40,
	0x10, 0x25, 0x4d, 0x7f, 0xfd, 0xa5, 0x1b, 0xa9, 0xb8, 0xa0, 0xc4, 0xa2, 0x28, 0x3d, 0x79, 0x69,
	0x02, 0x8a, 0x78, 0xf0, 0x26, 0x1e, 0xbc, 0x08, 0xb2, 0xde, 0xbc, 0xc8, 0x36, 0x0e, 0xc9, 0x42,
	0x92, 0xdd, 0x66, 0x26, 0x7e, 0x0c, 0x3f, 0xb3, 0xd3, 0x4d, 0x5a, 0xd1, 0x8b, 0x78, 0xda, 0x79,
	0x7f, 0x32, 0xef, 0x31, 0x11, 0xa7, 0x08, 0x15, 0xe4, 0x64, 0x6c, 0x93, 0xb9, 0xd6, 0x92, 0xcd,
	0x6a, 0x40, 0xd4, 0x05, 0xa4, 0x1e, 0xc9, 0x7f, 0xfe, 0x99, 0x1f, 0xa2, 0xae, 0x68, 0x30, 0x6c,
	0xc6, 0x5e, 0x9d, 0x27, 0x0e, 0xa0, 0xdd, 0xd2, 0xd0, 0xbe, 0x9b, 0x7c, 0xf8, 0x6e, 0xf1, 0x11,
	0x88, 0xd9, 0x13, 0x8b, 0xa6, 0x29, 0x14, 0xac, 0x3b, 0x40, 0x92, 0x33, 0x31, 0x22, 0x9b, 0x04,
	0xe7, 0xc1, 0xc5, 0x54, 0xf1, 0x24, 0x4f, 0xc4, 0x94, 0x0c, 0xa7, 0x91, 0xae, 0x5d, 0x32, 0x62,
	0x3a, 0x54, 0x5f, 0x84, 0x3c, 0x13, 0xe3, 0x4d, 0x50, 0x12, 0xb2, 0x10, 0x5f, 0xc6, 0xfd, 0xda,
	0xf4, 0x99, 0x29, 0xe5, 0x05, 0xb9, 0x14, 0xd1, 0x10, 0x89, 0xc9, 0xd8, 0x9b, 0x0e, 0xb6, 0xa6,
	0x9e, 0x7e, 0xd4, 0x4e, 0xed, 0x2c, 0x0b, 0x14, 0xfb, 0xbb, 0x3e, 0xe8, 0x6c, 0x83, 0x20, 0x8f,
	0x45, 0xd4, 0xc2, 0xfa, 0xb5, 0xd4, 0x58, 0xfa, 0x5a, 0x7b, 0xea, 0x3f, 0xe3, 0x07, 0x86, 0xf2,
	0x48, 0x4c, 0xb8, 0x06, 0x75, 0xe8, 0x8b, 0x45, 0x6a, 0x40, 0xdf, 0x42, 0xc3, 0xdf, 0x43, 0x6f,
	0x45, 0x3c, 0x84, 0xde, 0xb7, 0xd6, 0xfd, 0xed, 0x02, 0x77, 0x37, 0x2f, 0xd7, 0x85, 0xa1, 0xb2,
	0x5b, 0xa5, 0xb9, 0xad, 0x33, 0x63, 0x49, 0x57, 0xf0, 0x56, 0xf0, 0xbd, 0x75, 0x47, 0xd6, 0xf5,
	0x6b, 0x97, 0x68, 0xea, 0xec, 0xc7, 0x1f, 0x5c, 0x4d, 0xfc, 0x73, 0xf5, 0x19, 0x00, 0x00, 0xff,
	0xff, 0x67, 0x36, 0xc9, 0x87, 0xdb, 0x01, 0x00, 0x00,
}
