version: "3.5"

services:
  drand-client-1:
    container_name: testdrng-drand_0
    image: angelocapossele/drand:v1.1.4
    entrypoint: /data/client-script.sh
    ports:
      - "8000:8000/tcp"
      - "8800:8081/tcp"
    environment:
      LEADER: 1
      GOSHIMMER: "http://peer_master:8080"
  
  drand-client-2:
    container_name: drand2
    image: angelocapossele/drand:v1.1.4
    entrypoint: /data/client-script.sh
    ports:
      - "8001:8000/tcp"
      - "8801:8081/tcp"
    environment:
      GOSHIMMER: "http://peer_master:8080"
    depends_on:
      - drand-client-1

  drand-client-3:
    container_name: drand3
    image: angelocapossele/drand:v1.1.4
    entrypoint: /data/client-script.sh
    ports:
      - "8002:8000/tcp"
      - "8802:8081/tcp"
    environment:
      GOSHIMMER: "http://peer_master:8080"
    depends_on:
      - drand-client-1

  drand-client-4:
    container_name: drand4
    image: angelocapossele/drand:v1.1.4
    entrypoint: /data/client-script.sh
    ports:
      - "8003:8000/tcp"
      - "8803:8081/tcp"
    environment:
      GOSHIMMER: "http://peer_master:8080"
    depends_on:
      - drand-client-1
      
  drand-client-5:
    container_name: drand5
    image: angelocapossele/drand:v1.1.4
    entrypoint: /data/client-script.sh
    ports:
      - "8004:8000/tcp"
      - "8804:8081/tcp"
    environment:
      GOSHIMMER: "http://peer_master:8080"
    depends_on:
      - drand-client-1
