package bundle

const (
	MARSHALED_TRANSACTIONS_COUNT_START  = 0
	MARSHALED_HASH_START                = MARSHALED_TRANSACTIONS_COUNT_END
	MARSHALED_BUNDLE_ESSENCE_HASH_START = MARSHALED_HASH_END
	MARSHALED_FLAGS_START               = MARSHALED_BUNDLE_ESSENCE_HASH_END
	MARSHALED_APPROVERS_HASHES_START    = MARSHALED_FLAGS_END

	MARSHALED_TRANSACTIONS_COUNT_END  = MARSHALED_TRANSACTIONS_COUNT_START + MARSHALED_TRANSACTIONS_COUNT_SIZE
	MARSHALED_HASH_END                = MARSHALED_HASH_START + MARSHALED_TRANSACTION_HASH_SIZE
	MARSHALED_BUNDLE_ESSENCE_HASH_END = MARSHALED_BUNDLE_ESSENCE_HASH_START + MARSHALED_BUNDLE_ESSENCE_HASH_SIZE
	MARSHALED_FLAGS_END               = MARSHALED_FLAGS_START + MARSHALED_FLAGS_SIZE

	MARSHALED_TRANSACTIONS_COUNT_SIZE  = 8
	MARSHALED_TRANSACTION_HASH_SIZE    = 81
	MARSHALED_BUNDLE_ESSENCE_HASH_SIZE = 81
	MARSHALED_FLAGS_SIZE               = 1
	MARSHALED_MIN_SIZE                 = MARSHALED_TRANSACTIONS_COUNT_SIZE + MARSHALED_TRANSACTION_HASH_SIZE + MARSHALED_BUNDLE_ESSENCE_HASH_SIZE + MARSHALED_FLAGS_SIZE
)
