// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/message.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Ping struct {
	// protocol version number
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// string form of the return address (e.g. "192.0.2.1:25", "[2001:db8::1]:80")
	From string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	// string form of the recipient address
	To                   string   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{0}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Ping) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Ping) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

type Pong struct {
	// string form of the recipient address
	To string `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	// hash of the ping packet
	PingHash             []byte   `protobuf:"bytes,2,opt,name=ping_hash,json=pingHash,proto3" json:"ping_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{1}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Pong) GetPingHash() []byte {
	if m != nil {
		return m.PingHash
	}
	return nil
}

// wrapper to contain all the different messages
type MessageWrapper struct {
	// Types that are valid to be assigned to Message:
	//	*MessageWrapper_Ping
	//	*MessageWrapper_Pong
	Message              isMessageWrapper_Message `protobuf_oneof:"message"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *MessageWrapper) Reset()         { *m = MessageWrapper{} }
func (m *MessageWrapper) String() string { return proto.CompactTextString(m) }
func (*MessageWrapper) ProtoMessage()    {}
func (*MessageWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{2}
}

func (m *MessageWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageWrapper.Unmarshal(m, b)
}
func (m *MessageWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageWrapper.Marshal(b, m, deterministic)
}
func (m *MessageWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageWrapper.Merge(m, src)
}
func (m *MessageWrapper) XXX_Size() int {
	return xxx_messageInfo_MessageWrapper.Size(m)
}
func (m *MessageWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_MessageWrapper proto.InternalMessageInfo

type isMessageWrapper_Message interface {
	isMessageWrapper_Message()
}

type MessageWrapper_Ping struct {
	Ping *Ping `protobuf:"bytes,1,opt,name=ping,proto3,oneof"`
}

type MessageWrapper_Pong struct {
	Pong *Pong `protobuf:"bytes,2,opt,name=pong,proto3,oneof"`
}

func (*MessageWrapper_Ping) isMessageWrapper_Message() {}

func (*MessageWrapper_Pong) isMessageWrapper_Message() {}

func (m *MessageWrapper) GetMessage() isMessageWrapper_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *MessageWrapper) GetPing() *Ping {
	if x, ok := m.GetMessage().(*MessageWrapper_Ping); ok {
		return x.Ping
	}
	return nil
}

func (m *MessageWrapper) GetPong() *Pong {
	if x, ok := m.GetMessage().(*MessageWrapper_Pong); ok {
		return x.Pong
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*MessageWrapper) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MessageWrapper_Ping)(nil),
		(*MessageWrapper_Pong)(nil),
	}
}

func init() {
	proto.RegisterType((*Ping)(nil), "proto.Ping")
	proto.RegisterType((*Pong)(nil), "proto.Pong")
	proto.RegisterType((*MessageWrapper)(nil), "proto.MessageWrapper")
}

func init() { proto.RegisterFile("proto/message.proto", fileDescriptor_33f3a5e1293a7bcd) }

var fileDescriptor_33f3a5e1293a7bcd = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x4c, 0x8f, 0x41, 0x4f, 0x84, 0x30,
	0x10, 0x85, 0x65, 0x45, 0x57, 0x66, 0x75, 0x0f, 0xf5, 0xd2, 0xc4, 0x8b, 0x62, 0x4c, 0x3c, 0xd1,
	0xc4, 0xfd, 0x07, 0x1b, 0x0f, 0x7b, 0x31, 0x31, 0xbd, 0x98, 0x78, 0x31, 0x85, 0x54, 0x20, 0x01,
	0xa6, 0x69, 0x8b, 0xfe, 0x7d, 0x87, 0x01, 0x12, 0x4f, 0x33, 0xef, 0xcd, 0xe3, 0xe3, 0x15, 0x6e,
	0x9d, 0xc7, 0x88, 0xaa, 0xb7, 0x21, 0x98, 0xda, 0x16, 0xac, 0xc4, 0x05, 0x8f, 0xfc, 0x15, 0xd2,
	0xf7, 0x76, 0xa8, 0x85, 0x84, 0xed, 0x8f, 0xf5, 0xa1, 0xc5, 0x41, 0x26, 0xf7, 0xc9, 0xf3, 0x8d,
	0x5e, 0xa5, 0x10, 0x90, 0x7e, 0x7b, 0xec, 0xe5, 0x86, 0xec, 0x4c, 0xf3, 0x2e, 0xf6, 0xb0, 0x89,
	0x28, 0xcf, 0xd9, 0xa1, 0x2d, 0x3f, 0x10, 0x05, 0x89, 0x32, 0xfb, 0xc9, 0xea, 0x8b, 0x3b, 0xc8,
	0x1c, 0xd1, 0xbf, 0x1a, 0x13, 0x1a, 0x06, 0x5c, 0xeb, 0xab, 0xc9, 0x38, 0x91, 0xce, 0x0d, 0xec,
	0xdf, 0xe6, 0x4a, 0x1f, 0xde, 0x38, 0x67, 0xbd, 0x78, 0x80, 0x74, 0xba, 0x32, 0x60, 0xf7, 0xb2,
	0x9b, 0x9b, 0x16, 0x53, 0xbf, 0xd3, 0x99, 0xe6, 0x13, 0x47, 0xe8, 0x4f, 0x0c, 0xfb, 0x17, 0xc1,
	0x25, 0x42, 0xf3, 0x98, 0xc1, 0x76, 0x79, 0xea, 0xf1, 0xe9, 0xf3, 0xb1, 0x6e, 0x63, 0x33, 0x96,
	0x45, 0x85, 0xbd, 0xfa, 0xc5, 0xae, 0x33, 0x95, 0x32, 0x63, 0x44, 0x67, 0xad, 0x27, 0x9c, 0xe2,
	0xcf, 0xcb, 0x4b, 0x1e, 0x87, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe0, 0x77, 0xf0, 0x4a, 0x29,
	0x01, 0x00, 0x00,
}
