// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/message.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	proto1 "github.com/wollac/autopeering/peer/proto"
	proto2 "github.com/wollac/autopeering/salt/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Ping struct {
	// protocol version number
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// string form of the return address (e.g. "192.0.2.1:25", "[2001:db8::1]:80")
	From string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	// string form of the recipient address
	To string `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	// unix time
	Timestamp            int64    `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{0}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Ping) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Ping) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Ping) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type Pong struct {
	// hash of the ping packet
	PingHash []byte `protobuf:"bytes,1,opt,name=ping_hash,json=pingHash,proto3" json:"ping_hash,omitempty"`
	// string form of the recipient address
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{1}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetPingHash() []byte {
	if m != nil {
		return m.PingHash
	}
	return nil
}

func (m *Pong) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

type PeersRequest struct {
	// unix time
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeersRequest) Reset()         { *m = PeersRequest{} }
func (m *PeersRequest) String() string { return proto.CompactTextString(m) }
func (*PeersRequest) ProtoMessage()    {}
func (*PeersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{2}
}

func (m *PeersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeersRequest.Unmarshal(m, b)
}
func (m *PeersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeersRequest.Marshal(b, m, deterministic)
}
func (m *PeersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeersRequest.Merge(m, src)
}
func (m *PeersRequest) XXX_Size() int {
	return xxx_messageInfo_PeersRequest.Size(m)
}
func (m *PeersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PeersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PeersRequest proto.InternalMessageInfo

func (m *PeersRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type PeersResponse struct {
	// hash of the corresponding request
	ReqHash []byte `protobuf:"bytes,1,opt,name=req_hash,json=reqHash,proto3" json:"req_hash,omitempty"`
	// list of peers
	Peers                []*proto1.Peer `protobuf:"bytes,2,rep,name=peers,proto3" json:"peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PeersResponse) Reset()         { *m = PeersResponse{} }
func (m *PeersResponse) String() string { return proto.CompactTextString(m) }
func (*PeersResponse) ProtoMessage()    {}
func (*PeersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{3}
}

func (m *PeersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeersResponse.Unmarshal(m, b)
}
func (m *PeersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeersResponse.Marshal(b, m, deterministic)
}
func (m *PeersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeersResponse.Merge(m, src)
}
func (m *PeersResponse) XXX_Size() int {
	return xxx_messageInfo_PeersResponse.Size(m)
}
func (m *PeersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PeersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PeersResponse proto.InternalMessageInfo

func (m *PeersResponse) GetReqHash() []byte {
	if m != nil {
		return m.ReqHash
	}
	return nil
}

func (m *PeersResponse) GetPeers() []*proto1.Peer {
	if m != nil {
		return m.Peers
	}
	return nil
}

type PeeringRequest struct {
	// string form of the recipient address
	To string `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	// unix time
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// salt of the requester
	Salt                 *proto2.Salt `protobuf:"bytes,3,opt,name=salt,proto3" json:"salt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PeeringRequest) Reset()         { *m = PeeringRequest{} }
func (m *PeeringRequest) String() string { return proto.CompactTextString(m) }
func (*PeeringRequest) ProtoMessage()    {}
func (*PeeringRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{4}
}

func (m *PeeringRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeeringRequest.Unmarshal(m, b)
}
func (m *PeeringRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeeringRequest.Marshal(b, m, deterministic)
}
func (m *PeeringRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeeringRequest.Merge(m, src)
}
func (m *PeeringRequest) XXX_Size() int {
	return xxx_messageInfo_PeeringRequest.Size(m)
}
func (m *PeeringRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PeeringRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PeeringRequest proto.InternalMessageInfo

func (m *PeeringRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *PeeringRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *PeeringRequest) GetSalt() *proto2.Salt {
	if m != nil {
		return m.Salt
	}
	return nil
}

type PeeringResponse struct {
	// hash of the corresponding request
	ReqHash []byte `protobuf:"bytes,1,opt,name=req_hash,json=reqHash,proto3" json:"req_hash,omitempty"`
	// response of a peering request
	Status               bool     `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeeringResponse) Reset()         { *m = PeeringResponse{} }
func (m *PeeringResponse) String() string { return proto.CompactTextString(m) }
func (*PeeringResponse) ProtoMessage()    {}
func (*PeeringResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{5}
}

func (m *PeeringResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeeringResponse.Unmarshal(m, b)
}
func (m *PeeringResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeeringResponse.Marshal(b, m, deterministic)
}
func (m *PeeringResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeeringResponse.Merge(m, src)
}
func (m *PeeringResponse) XXX_Size() int {
	return xxx_messageInfo_PeeringResponse.Size(m)
}
func (m *PeeringResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PeeringResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PeeringResponse proto.InternalMessageInfo

func (m *PeeringResponse) GetReqHash() []byte {
	if m != nil {
		return m.ReqHash
	}
	return nil
}

func (m *PeeringResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type PeeringDrop struct {
	// string form of the recipient address
	To string `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	// unix time
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeeringDrop) Reset()         { *m = PeeringDrop{} }
func (m *PeeringDrop) String() string { return proto.CompactTextString(m) }
func (*PeeringDrop) ProtoMessage()    {}
func (*PeeringDrop) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{6}
}

func (m *PeeringDrop) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeeringDrop.Unmarshal(m, b)
}
func (m *PeeringDrop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeeringDrop.Marshal(b, m, deterministic)
}
func (m *PeeringDrop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeeringDrop.Merge(m, src)
}
func (m *PeeringDrop) XXX_Size() int {
	return xxx_messageInfo_PeeringDrop.Size(m)
}
func (m *PeeringDrop) XXX_DiscardUnknown() {
	xxx_messageInfo_PeeringDrop.DiscardUnknown(m)
}

var xxx_messageInfo_PeeringDrop proto.InternalMessageInfo

func (m *PeeringDrop) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *PeeringDrop) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

// wrapper to contain all the different messages
type MessageWrapper struct {
	// Types that are valid to be assigned to Message:
	//	*MessageWrapper_Ping
	//	*MessageWrapper_Pong
	//	*MessageWrapper_PeersRequest
	//	*MessageWrapper_PeersResponse
	//	*MessageWrapper_PeeringRequest
	//	*MessageWrapper_PeeringResponse
	//	*MessageWrapper_PeeringDrop
	Message              isMessageWrapper_Message `protobuf_oneof:"message"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *MessageWrapper) Reset()         { *m = MessageWrapper{} }
func (m *MessageWrapper) String() string { return proto.CompactTextString(m) }
func (*MessageWrapper) ProtoMessage()    {}
func (*MessageWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{7}
}

func (m *MessageWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageWrapper.Unmarshal(m, b)
}
func (m *MessageWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageWrapper.Marshal(b, m, deterministic)
}
func (m *MessageWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageWrapper.Merge(m, src)
}
func (m *MessageWrapper) XXX_Size() int {
	return xxx_messageInfo_MessageWrapper.Size(m)
}
func (m *MessageWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_MessageWrapper proto.InternalMessageInfo

type isMessageWrapper_Message interface {
	isMessageWrapper_Message()
}

type MessageWrapper_Ping struct {
	Ping *Ping `protobuf:"bytes,1,opt,name=ping,proto3,oneof"`
}

type MessageWrapper_Pong struct {
	Pong *Pong `protobuf:"bytes,2,opt,name=pong,proto3,oneof"`
}

type MessageWrapper_PeersRequest struct {
	PeersRequest *PeersRequest `protobuf:"bytes,3,opt,name=peers_request,json=peersRequest,proto3,oneof"`
}

type MessageWrapper_PeersResponse struct {
	PeersResponse *PeersResponse `protobuf:"bytes,4,opt,name=peers_response,json=peersResponse,proto3,oneof"`
}

type MessageWrapper_PeeringRequest struct {
	PeeringRequest *PeeringRequest `protobuf:"bytes,5,opt,name=peering_request,json=peeringRequest,proto3,oneof"`
}

type MessageWrapper_PeeringResponse struct {
	PeeringResponse *PeeringResponse `protobuf:"bytes,6,opt,name=peering_response,json=peeringResponse,proto3,oneof"`
}

type MessageWrapper_PeeringDrop struct {
	PeeringDrop *PeeringDrop `protobuf:"bytes,7,opt,name=peering_drop,json=peeringDrop,proto3,oneof"`
}

func (*MessageWrapper_Ping) isMessageWrapper_Message() {}

func (*MessageWrapper_Pong) isMessageWrapper_Message() {}

func (*MessageWrapper_PeersRequest) isMessageWrapper_Message() {}

func (*MessageWrapper_PeersResponse) isMessageWrapper_Message() {}

func (*MessageWrapper_PeeringRequest) isMessageWrapper_Message() {}

func (*MessageWrapper_PeeringResponse) isMessageWrapper_Message() {}

func (*MessageWrapper_PeeringDrop) isMessageWrapper_Message() {}

func (m *MessageWrapper) GetMessage() isMessageWrapper_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *MessageWrapper) GetPing() *Ping {
	if x, ok := m.GetMessage().(*MessageWrapper_Ping); ok {
		return x.Ping
	}
	return nil
}

func (m *MessageWrapper) GetPong() *Pong {
	if x, ok := m.GetMessage().(*MessageWrapper_Pong); ok {
		return x.Pong
	}
	return nil
}

func (m *MessageWrapper) GetPeersRequest() *PeersRequest {
	if x, ok := m.GetMessage().(*MessageWrapper_PeersRequest); ok {
		return x.PeersRequest
	}
	return nil
}

func (m *MessageWrapper) GetPeersResponse() *PeersResponse {
	if x, ok := m.GetMessage().(*MessageWrapper_PeersResponse); ok {
		return x.PeersResponse
	}
	return nil
}

func (m *MessageWrapper) GetPeeringRequest() *PeeringRequest {
	if x, ok := m.GetMessage().(*MessageWrapper_PeeringRequest); ok {
		return x.PeeringRequest
	}
	return nil
}

func (m *MessageWrapper) GetPeeringResponse() *PeeringResponse {
	if x, ok := m.GetMessage().(*MessageWrapper_PeeringResponse); ok {
		return x.PeeringResponse
	}
	return nil
}

func (m *MessageWrapper) GetPeeringDrop() *PeeringDrop {
	if x, ok := m.GetMessage().(*MessageWrapper_PeeringDrop); ok {
		return x.PeeringDrop
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*MessageWrapper) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MessageWrapper_Ping)(nil),
		(*MessageWrapper_Pong)(nil),
		(*MessageWrapper_PeersRequest)(nil),
		(*MessageWrapper_PeersResponse)(nil),
		(*MessageWrapper_PeeringRequest)(nil),
		(*MessageWrapper_PeeringResponse)(nil),
		(*MessageWrapper_PeeringDrop)(nil),
	}
}

func init() {
	proto.RegisterType((*Ping)(nil), "proto.Ping")
	proto.RegisterType((*Pong)(nil), "proto.Pong")
	proto.RegisterType((*PeersRequest)(nil), "proto.PeersRequest")
	proto.RegisterType((*PeersResponse)(nil), "proto.PeersResponse")
	proto.RegisterType((*PeeringRequest)(nil), "proto.PeeringRequest")
	proto.RegisterType((*PeeringResponse)(nil), "proto.PeeringResponse")
	proto.RegisterType((*PeeringDrop)(nil), "proto.PeeringDrop")
	proto.RegisterType((*MessageWrapper)(nil), "proto.MessageWrapper")
}

func init() { proto.RegisterFile("proto/message.proto", fileDescriptor_33f3a5e1293a7bcd) }

var fileDescriptor_33f3a5e1293a7bcd = []byte{
	// 484 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x53, 0x4d, 0x8b, 0x13, 0x41,
	0x10, 0x35, 0xc9, 0xe4, 0xab, 0x26, 0x99, 0x48, 0xaf, 0xbb, 0x8c, 0x1f, 0xa0, 0x8e, 0x08, 0x7b,
	0x90, 0x04, 0x76, 0x0f, 0x82, 0x22, 0xc8, 0xba, 0x07, 0x2f, 0x0b, 0x4b, 0x7b, 0x10, 0xbc, 0x84,
	0xc9, 0xda, 0x26, 0x81, 0x24, 0xdd, 0xdb, 0xdd, 0xa3, 0x7f, 0xc6, 0x1f, 0x6b, 0x75, 0x75, 0x4f,
	0xe6, 0x03, 0x41, 0x3c, 0x4d, 0x57, 0x75, 0xd5, 0x7b, 0x6f, 0xde, 0x9b, 0x81, 0x13, 0xa5, 0xa5,
	0x95, 0x8b, 0xbd, 0x30, 0x26, 0x5f, 0x8b, 0x39, 0x55, 0xac, 0x4f, 0x8f, 0x27, 0xa7, 0x4a, 0x08,
	0xbd, 0xf0, 0x03, 0xee, 0x38, 0x0f, 0x6d, 0x93, 0xef, 0x6c, 0x68, 0xbb, 0xa3, 0x6f, 0x67, 0x2b,
	0x88, 0x6e, 0xb7, 0x87, 0x35, 0x4b, 0x61, 0xf8, 0x53, 0x68, 0xb3, 0x95, 0x87, 0xb4, 0xf3, 0xa2,
	0x73, 0x3e, 0xe5, 0x65, 0xc9, 0x18, 0x44, 0x3f, 0xb4, 0xdc, 0xa7, 0x5d, 0x6c, 0x8f, 0x39, 0x9d,
	0x59, 0x02, 0x5d, 0x2b, 0xd3, 0x1e, 0x75, 0xf0, 0xc4, 0x9e, 0xc1, 0xd8, 0x6e, 0x51, 0x8d, 0xcd,
	0xf7, 0x2a, 0x8d, 0xb0, 0xdd, 0xe3, 0x55, 0x23, 0xbb, 0x44, 0x0e, 0x89, 0x1c, 0x4f, 0x61, 0xac,
	0x90, 0x6b, 0xb9, 0xc9, 0xcd, 0x86, 0x58, 0x26, 0x7c, 0xe4, 0x1a, 0x9f, 0xb1, 0x0e, 0x90, 0xdd,
	0x12, 0x32, 0x7b, 0x03, 0x93, 0x5b, 0x54, 0x6f, 0xb8, 0xb8, 0x2f, 0x10, 0xa7, 0x49, 0xd1, 0x69,
	0x53, 0xdc, 0xc0, 0x34, 0x4c, 0x1b, 0x25, 0x0f, 0x46, 0xb0, 0xc7, 0x30, 0xd2, 0xe2, 0xbe, 0x4e,
	0x35, 0xc4, 0x9a, 0x98, 0x5e, 0x42, 0xdf, 0xf9, 0x62, 0x90, 0xac, 0x77, 0x1e, 0x5f, 0xc4, 0xde,
	0x89, 0xb9, 0xdb, 0xe7, 0xfe, 0x26, 0x5b, 0x42, 0xe2, 0x4a, 0xd4, 0x56, 0xd2, 0x7b, 0x79, 0x9d,
	0xbf, 0xbf, 0x71, 0xb7, 0x25, 0x87, 0x3d, 0x87, 0xc8, 0x79, 0x4c, 0x0e, 0x55, 0x0c, 0x5f, 0xb0,
	0xc5, 0xe9, 0x22, 0xbb, 0x86, 0xd9, 0x91, 0xe0, 0xdf, 0x8a, 0xcf, 0x60, 0x80, 0xb8, 0xb6, 0x30,
	0xc4, 0x34, 0xe2, 0xa1, 0xca, 0xde, 0x43, 0x1c, 0x50, 0xae, 0xb5, 0x54, 0xff, 0xa7, 0x31, 0xfb,
	0xdd, 0x83, 0xe4, 0xc6, 0x7f, 0x40, 0x5f, 0x75, 0xae, 0x94, 0xd0, 0xe8, 0x4c, 0xe4, 0xf2, 0x20,
	0x88, 0x9a, 0x31, 0x2e, 0xa2, 0x07, 0x9c, 0xae, 0x68, 0x04, 0xb3, 0x24, 0xb8, 0xda, 0x88, 0x0c,
	0x23, 0x2e, 0xe6, 0x77, 0x30, 0x25, 0x17, 0x97, 0xda, 0x7b, 0x17, 0x5c, 0x38, 0xa9, 0xf9, 0x5c,
	0xa6, 0x8a, 0x3b, 0x13, 0x55, 0x4f, 0xf9, 0x03, 0x24, 0xe5, 0xae, 0xb7, 0x85, 0xbe, 0xa6, 0xf8,
	0xe2, 0x51, 0x73, 0xd9, 0xdf, 0xe1, 0xf6, 0x54, 0x35, 0x52, 0xff, 0x08, 0x33, 0xe5, 0x0d, 0x39,
	0x92, 0xf7, 0x69, 0xff, 0xb4, 0xb6, 0x5f, 0xa5, 0x8a, 0x00, 0x89, 0x6a, 0xe6, 0xfc, 0x09, 0x1e,
	0x56, 0x08, 0x41, 0xc2, 0x80, 0x20, 0xce, 0xda, 0x10, 0x47, 0x11, 0x33, 0xd5, 0x8a, 0xf2, 0x2d,
	0x4c, 0x4a, 0x90, 0xef, 0x18, 0x4c, 0x3a, 0x24, 0x00, 0xd6, 0x04, 0x70, 0x91, 0xe1, 0x72, 0xac,
	0xaa, 0xf2, 0x6a, 0x0c, 0xc3, 0xf0, 0x4f, 0x5f, 0xbd, 0xfe, 0xf6, 0x6a, 0xbd, 0xb5, 0x9b, 0x62,
	0x35, 0xbf, 0x93, 0xfb, 0xc5, 0x2f, 0xb9, 0xdb, 0xe5, 0x77, 0x8b, 0xbc, 0xb0, 0x32, 0xcc, 0xfb,
	0x5f, 0x79, 0x35, 0xa0, 0xc7, 0xe5, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x61, 0x95, 0x78,
	0x12, 0x04, 0x00, 0x00,
}
