package epochtracker

import (
	"github.com/iotaledger/goshimmer/packages/core/epoch"
	"github.com/iotaledger/hive.go/core/generics/event"
	"github.com/iotaledger/hive.go/core/identity"
	"github.com/iotaledger/hive.go/runtime/event"
)

type Events struct {
	VotersUpdated *event.Event1[*VoterUpdatedEvent]

	event.Group[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.CreateGroupConstructor(func() (newEvents *Events) {
	return &Events{
		VotersUpdated: event.New1[*VoterUpdatedEvent](),
	}
})

type VoterUpdatedEvent struct {
	Voter                identity.ID
	NewLatestEpochIndex  epoch.Index
	PrevLatestEpochIndex epoch.Index
}
