// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "f5a453b2225a53b99888566530e196c2"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"46035eeeaf7e567dd2351f78b7066772": "1f8b08000000000000ff5c8f314ec4400c45fb48b9832928b35a0a9ad98e03700767c62416c61e394e08a0bd3b45c28a4dfbde7ccd73db9caad3f24a6bbccc11a6f0d3360000416b7485b239069b2650538207fea8e6811a97ed5936314fd00be6f71d552c8575e884de22c1735d0fdc7918efc4421e9c513a141e3441260df2cbbf8ea3b8b64ddb9c462e856ec10b4fdcb3707c25d8cd5dedb659789a51f89bfc6f576de2ed42ec27933968ff79a42df4e97c7edcd12797186fe4fa1b0000ffffa045f6503d010000",
		"a531f1ecaa4c59f1b1b4d21b3a1bcddf": "1f8b08000000000000ff5491514b2b311085dff757e4e6f5d2cdedddc556c92e88825228a5b562f52d4dd2cde8265992e9dafc7ba9db2acd4b66ce77380c33fc8ff21253a78941dbd6193f7f5aa83a2384106e350a228d08516345f7b81b4de9092160abeb07ff64c05a1dc8ad136d8a3a703690c1d582fbf8aece2fe8b6a21153aba3d11ae9053441ef2a6a10bb78c3981507a95cbef51e2306d11d1be92dfb11589917f998c9187fb5dc82cb658c97c1e05037013055341a514ccb51d32cd2ea1f6ceeb6f3655f6ca0b3a228e7f77fd5231bef969369c9deafe42b83d97af9bc30f2254c0ed7b3deaf0eebfff3b7cff1fa325f061fa30fd080aba870de25ebf7a719589d7136ec946fbd4a75c615f404544583f7486bce14f447d389b2e10e5f010000ffff4361a5da9f010000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("AnalysisDashboard_Assets", "./frontend/src/assets")
		b.SetResolver("index.html", packr.Pointer{ForwardBox: gk, ForwardPath: "a531f1ecaa4c59f1b1b4d21b3a1bcddf"})
		b.SetResolver("main.css", packr.Pointer{ForwardBox: gk, ForwardPath: "46035eeeaf7e567dd2351f78b7066772"})
	}()
	return nil
}()
