package signatures

import "github.com/iotaledger/goshimmer/packages/binary/valuetransfer/address"

// SignatureScheme defines an interface for different signature generation methods (i.e. ED25519, WOTS, and so on ...).
type SignatureScheme interface {
	// Version returns the version byte that is associated to this signature scheme.
	Version() byte

	// Address returns the address that this signature scheme instance is securing.
	Address() address.Address

	// Sign creates a valid signature for the given data according to the signature scheme implementation.
	Sign(data []byte) Signature
}

// Signature defines an interface for an address signature generated by the corresponding signature scheme.
type Signature interface {
	// IsValid returns true if the signature is valid for the given data.
	IsValid(signedData []byte) bool

	// Bytes returns a marshaled version of the signature.
	Bytes() []byte

	// Address returns the address, that this signature signs.
	Address() address.Address
}
