- name: Generate key materials in leader Drand
  community.docker.docker_container_exec:
    container: drand{{ drandNumber }}
    command: drand share --connect "{{ leaderDrandAddress }}" --tls-disable --nodes {{ numberOfDrands }} --threshold {{ drandsThreshold }} --secret "{{ drandsSecret }}" --catchup-period 0