- name: Create directory
  file:
    path: /opt/drand{{ drandNumber }}
    state: directory
    mode: '0755'


- name: Template docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: /opt/drand{{ drandNumber }}/docker-compose.yml
    mode: '0644'

- name: Stop existing services gracefully
  community.general.docker_compose:
    project_src: /opt/drand{{ drandNumber }}
    timeout: 180
    state: present
    stopped: yes

- name: Tear down existing services
  community.general.docker_compose:
    project_src: /opt/drand{{ drandNumber }}
    state: absent
    remove_volumes: yes

- name: Run drand
  community.general.docker_compose:
    project_src: /opt/drand{{ drandNumber }}
    timeout: 180
    state: present
    pull: yes