package permanent

import (
	"github.com/iotaledger/hive.go/core/generics/event"
	"github.com/iotaledger/hive.go/core/identity"

	"github.com/iotaledger/goshimmer/packages/storage/models"
)

type Events struct {
	ConsensusWeightsUpdated *event.Linkable[map[identity.ID]*models.TimedBalance]

	event.LinkableCollection[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.LinkableConstructor(func() (self *Events) {
	return &Events{
		ConsensusWeightsUpdated: event.NewLinkable[map[identity.ID]*models.TimedBalance](),
	}
})
