// Code generated by protoc-gen-go. DO NOT EDIT.
// source: salt/proto/salt.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Salt struct {
	// value of the salt
	Bytes []byte `protobuf:"bytes,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
	// expiration time of the salt
	ExpTime              uint64   `protobuf:"fixed64,2,opt,name=exp_time,json=expTime,proto3" json:"exp_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Salt) Reset()         { *m = Salt{} }
func (m *Salt) String() string { return proto.CompactTextString(m) }
func (*Salt) ProtoMessage()    {}
func (*Salt) Descriptor() ([]byte, []int) {
	return fileDescriptor_d46762658484b01f, []int{0}
}

func (m *Salt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Salt.Unmarshal(m, b)
}
func (m *Salt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Salt.Marshal(b, m, deterministic)
}
func (m *Salt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Salt.Merge(m, src)
}
func (m *Salt) XXX_Size() int {
	return xxx_messageInfo_Salt.Size(m)
}
func (m *Salt) XXX_DiscardUnknown() {
	xxx_messageInfo_Salt.DiscardUnknown(m)
}

var xxx_messageInfo_Salt proto.InternalMessageInfo

func (m *Salt) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

func (m *Salt) GetExpTime() uint64 {
	if m != nil {
		return m.ExpTime
	}
	return 0
}

func init() {
	proto.RegisterType((*Salt)(nil), "proto.Salt")
}

func init() { proto.RegisterFile("salt/proto/salt.proto", fileDescriptor_d46762658484b01f) }

var fileDescriptor_d46762658484b01f = []byte{
	// 142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x4e, 0xcc, 0x29,
	0xd1, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x07, 0x31, 0xf5, 0xc0, 0x4c, 0x21, 0x56, 0x30, 0xa5,
	0x64, 0xce, 0xc5, 0x12, 0x0c, 0x14, 0x14, 0x12, 0xe1, 0x62, 0x4d, 0xaa, 0x2c, 0x49, 0x2d, 0x96,
	0x60, 0x54, 0x60, 0xd4, 0xe0, 0x09, 0x82, 0x70, 0x84, 0x24, 0xb9, 0x38, 0x52, 0x2b, 0x0a, 0xe2,
	0x4b, 0x32, 0x73, 0x53, 0x25, 0x98, 0x80, 0x12, 0x6c, 0x41, 0xec, 0x40, 0x7e, 0x08, 0x90, 0xeb,
	0x64, 0x14, 0x65, 0x90, 0x9e, 0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c, 0x9f, 0xab, 0x9f, 0x99,
	0x5f, 0x92, 0x98, 0x93, 0x9a, 0x92, 0x9e, 0x5a, 0xa4, 0x9f, 0x58, 0x5a, 0x92, 0x5f, 0x90, 0x9a,
	0x5a, 0x94, 0x99, 0x97, 0xae, 0x5b, 0x9c, 0x99, 0xab, 0x8f, 0xb0, 0x3e, 0x89, 0x0d, 0x4c, 0x19,
	0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x47, 0x07, 0x7d, 0x5f, 0x93, 0x00, 0x00, 0x00,
}
