package blockgadget

import (
	"github.com/iotaledger/goshimmer/packages/core/memstorage"
	"github.com/iotaledger/goshimmer/packages/protocol/models"
	"github.com/iotaledger/hive.go/core/generics/event"
)

type Events struct {
	BlockAccepted  *event.Linkable[*Block]
	BlockConfirmed *event.Linkable[*Block]
	EpochClosed    *event.Linkable[*memstorage.Storage[models.BlockID, *Block]]
	Error          *event.Linkable[error]

	event.LinkableCollection[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.LinkableConstructor(func() (newEvents *Events) {
	return &Events{
		BlockAccepted:  event.NewLinkable[*Block](),
		BlockConfirmed: event.NewLinkable[*Block](),
		EpochClosed:    event.NewLinkable[*memstorage.Storage[models.BlockID, *Block]](),
		Error:          event.NewLinkable[error](),
	}
})
