package eviction

import (
	"github.com/iotaledger/hive.go/core/generics/event"

	"github.com/iotaledger/goshimmer/packages/core/epoch"
)

type Events struct {
	EpochEvicted *event.Linkable[epoch.Index]

	event.LinkableCollection[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.LinkableConstructor(func() (self *Events) {
	return &Events{
		EpochEvicted: event.NewLinkable[epoch.Index](),
	}
})
