// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server/proto/handshake.proto

package proto

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HandshakeRequest struct {
	// protocol version number
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// string form of the recipient address
	To string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	// unix time
	Timestamp            int64    `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandshakeRequest) Reset()         { *m = HandshakeRequest{} }
func (m *HandshakeRequest) String() string { return proto.CompactTextString(m) }
func (*HandshakeRequest) ProtoMessage()    {}
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7101ffe19b05443, []int{0}
}

func (m *HandshakeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandshakeRequest.Unmarshal(m, b)
}
func (m *HandshakeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandshakeRequest.Marshal(b, m, deterministic)
}
func (m *HandshakeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandshakeRequest.Merge(m, src)
}
func (m *HandshakeRequest) XXX_Size() int {
	return xxx_messageInfo_HandshakeRequest.Size(m)
}
func (m *HandshakeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HandshakeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HandshakeRequest proto.InternalMessageInfo

func (m *HandshakeRequest) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *HandshakeRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *HandshakeRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type HandshakeResponse struct {
	// hash of the ping packet
	ReqHash              []byte   `protobuf:"bytes,1,opt,name=req_hash,json=reqHash,proto3" json:"req_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandshakeResponse) Reset()         { *m = HandshakeResponse{} }
func (m *HandshakeResponse) String() string { return proto.CompactTextString(m) }
func (*HandshakeResponse) ProtoMessage()    {}
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7101ffe19b05443, []int{1}
}

func (m *HandshakeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandshakeResponse.Unmarshal(m, b)
}
func (m *HandshakeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandshakeResponse.Marshal(b, m, deterministic)
}
func (m *HandshakeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandshakeResponse.Merge(m, src)
}
func (m *HandshakeResponse) XXX_Size() int {
	return xxx_messageInfo_HandshakeResponse.Size(m)
}
func (m *HandshakeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HandshakeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HandshakeResponse proto.InternalMessageInfo

func (m *HandshakeResponse) GetReqHash() []byte {
	if m != nil {
		return m.ReqHash
	}
	return nil
}

func init() {
	proto.RegisterType((*HandshakeRequest)(nil), "proto.HandshakeRequest")
	proto.RegisterType((*HandshakeResponse)(nil), "proto.HandshakeResponse")
}

func init() { proto.RegisterFile("server/proto/handshake.proto", fileDescriptor_d7101ffe19b05443) }

var fileDescriptor_d7101ffe19b05443 = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x5c, 0x8f, 0x31, 0x4b, 0x83, 0x31,
	0x10, 0x86, 0x69, 0x8b, 0xd6, 0x06, 0x15, 0xcd, 0xf4, 0x09, 0x82, 0xd2, 0xc9, 0xe9, 0xcb, 0xe0,
	0x0f, 0x10, 0x9d, 0x3a, 0x67, 0xec, 0x22, 0xd7, 0xf6, 0x48, 0x42, 0x4d, 0x2e, 0xcd, 0x5d, 0xfd,
	0xfd, 0x9e, 0x81, 0xa2, 0x74, 0x7a, 0xdf, 0xe7, 0x09, 0x79, 0x49, 0xcc, 0x93, 0x34, 0x28, 0x5c,
	0xa9, 0x89, 0xab, 0x8d, 0x84, 0x5c, 0x84, 0xb2, 0xe3, 0x08, 0x7b, 0x1c, 0x3b, 0xdb, 0x8b, 0x1e,
	0xcb, 0xb5, 0xb9, 0x5b, 0x9d, 0x4e, 0x3c, 0x1e, 0x8e, 0xc8, 0x62, 0x07, 0x33, 0xff, 0xc6, 0xc6,
	0x89, 0xca, 0x30, 0x79, 0x9e, 0xbc, 0xdc, 0xf8, 0x13, 0xda, 0x5b, 0x33, 0x15, 0x1a, 0xa6, 0x2a,
	0x17, 0x5e, 0x9b, 0x7d, 0x34, 0x0b, 0x49, 0x59, 0xef, 0x40, 0xae, 0xc3, 0x4c, 0xf5, 0xcc, 0xff,
	0x89, 0xe5, 0x68, 0xee, 0xff, 0x6d, 0xeb, 0x63, 0x0a, 0xa3, 0x7d, 0x30, 0x57, 0x0d, 0x0f, 0x9f,
	0x11, 0x38, 0xf6, 0xf5, 0x6b, 0x3f, 0x57, 0x5e, 0x29, 0x7e, 0xbc, 0xaf, 0xdf, 0x42, 0x92, 0x78,
	0xdc, 0x8c, 0x5b, 0xca, 0x2e, 0x91, 0xc0, 0x17, 0xee, 0x02, 0x36, 0x17, 0x88, 0x63, 0xca, 0x59,
	0x5b, 0x85, 0xed, 0x1e, 0x02, 0xf2, 0xaf, 0xe2, 0x54, 0xdd, 0xd9, 0x2f, 0x37, 0x97, 0x3d, 0x5e,
	0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x51, 0x6a, 0x20, 0xf4, 0xff, 0x00, 0x00, 0x00,
}
