package eviction

import (
	"github.com/iotaledger/goshimmer/packages/core/epoch"
	"github.com/iotaledger/hive.go/runtime/event"
)

type Events struct {
	EpochEvicted *event.Event1[epoch.Index]

	event.Group[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.CreateGroupConstructor(func() (self *Events) {
	return &Events{
		EpochEvicted: event.New1[epoch.Index](),
	}
})
