package booker

import (
	"github.com/iotaledger/goshimmer/packages/protocol/engine/tangle/booker/markermanager"
	"github.com/iotaledger/goshimmer/packages/protocol/engine/tangle/booker/markers"
	"github.com/iotaledger/goshimmer/packages/protocol/ledger/utxo"
	"github.com/iotaledger/hive.go/runtime/event"
)

type Events struct {
	BlockBooked         *event.Event1[*BlockBookedEvent]
	AttachmentCreated   *event.Event1[*Block]
	AttachmentOrphaned  *event.Event1[*Block]
	BlockConflictAdded  *event.Event1[*BlockConflictAddedEvent]
	MarkerConflictAdded *event.Event1[*MarkerConflictAddedEvent]
	Error               *event.Event1[error]

	MarkerManager *markermanager.Events

	event.Group[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.CreateGroupConstructor(func() (newEvents *Events) {
	return &Events{
		BlockBooked:         event.New1[*BlockBookedEvent](),
		AttachmentCreated:   event.New1[*Block](),
		AttachmentOrphaned:  event.New1[*Block](),
		BlockConflictAdded:  event.New1[*BlockConflictAddedEvent](),
		MarkerConflictAdded: event.New1[*MarkerConflictAddedEvent](),
		Error:               event.New1[error](),

		MarkerManager: markermanager.NewEvents(),
	}
})

type BlockConflictAddedEvent struct {
	Block             *Block
	ConflictID        utxo.TransactionID
	ParentConflictIDs utxo.TransactionIDs
}

type MarkerConflictAddedEvent struct {
	Marker            markers.Marker
	ConflictID        utxo.TransactionID
	ParentConflictIDs utxo.TransactionIDs
}

type BlockBookedEvent struct {
	Block       *Block
	ConflictIDs utxo.TransactionIDs
}
