package consensus

import (
	"github.com/iotaledger/hive.go/core/generics/event"

	"github.com/iotaledger/goshimmer/packages/protocol/engine/consensus/blockgadget"
	"github.com/iotaledger/goshimmer/packages/protocol/engine/consensus/epochgadget"
)

type Events struct {
	Acceptance        *blockgadget.Events
	EpochConfirmation *epochgadget.Events

	event.LinkableCollection[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.LinkableConstructor(func() (newEvents *Events) {
	return &Events{
		Acceptance:        blockgadget.NewEvents(),
		EpochConfirmation: epochgadget.NewEvents(),
	}
})
