package consensus

import (
	"github.com/iotaledger/hive.go/core/generics/event"

	"github.com/iotaledger/goshimmer/packages/protocol/engine/consensus/acceptance"
	"github.com/iotaledger/goshimmer/packages/protocol/engine/consensus/epochconfirmation"
)

type Events struct {
	Acceptance        *acceptance.Events
	EpochConfirmation *epochconfirmation.Events

	event.LinkableCollection[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.LinkableConstructor(func() (newEvents *Events) {
	return &Events{
		Acceptance:        acceptance.NewEvents(),
		EpochConfirmation: epochconfirmation.NewEvents(),
	}
})
