package commitmenttracker

import (
	"github.com/iotaledger/hive.go/core/generics/event"

	"github.com/iotaledger/goshimmer/packages/core/epoch"
	"github.com/iotaledger/goshimmer/packages/core/validator"
)

type Events struct {
	VotersUpdated *event.Linkable[*VoterUpdatedEvent]

	event.LinkableCollection[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.LinkableConstructor(func() (newEvents *Events) {
	return &Events{
		VotersUpdated: event.NewLinkable[*VoterUpdatedEvent](),
	}
})

type VoterUpdatedEvent struct {
	Voter                *validator.Validator
	NewLatestEpochIndex  epoch.Index
	PrevLatestEpochIndex epoch.Index
}
