package engine

import (
	"github.com/iotaledger/hive.go/core/generics/event"

	"github.com/iotaledger/goshimmer/packages/protocol/engine/clock"
	"github.com/iotaledger/goshimmer/packages/protocol/engine/congestioncontrol"
	"github.com/iotaledger/goshimmer/packages/protocol/engine/consensus"
	"github.com/iotaledger/goshimmer/packages/protocol/engine/tangle"
)

type Events struct {
	Tangle            *tangle.Events
	CongestionControl *congestioncontrol.Events
	Clock             *clock.Events
	Consensus         *consensus.Events

	event.LinkableCollection[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.LinkableConstructor(func() (newEvents *Events) {
	return &Events{
		Tangle:            tangle.NewEvents(),
		CongestionControl: congestioncontrol.NewEvents(),
		Clock:             clock.NewEvents(),
	}
})
