package engine

import (
	"github.com/iotaledger/hive.go/core/generics/event"

	"github.com/iotaledger/goshimmer/packages/protocol/engine/tangle"
)

type Events struct {
	Tangle *tangle.Events

	event.LinkableCollection[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.LinkableCollectionConstructor[Events](func(e *Events) {
	e.Tangle = tangle.NewEvents()

	e.OnLinkUpdated(func(linkTarget *Events) {
		e.Tangle.LinkTo(linkTarget.Tangle)
	})
})
