package engine

import (
	"github.com/iotaledger/hive.go/core/generics/event"

	"github.com/iotaledger/goshimmer/packages/protocol/engine/tangle"
)

type Events struct {
	Tangle *tangle.Events

	event.LinkableCollection[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.NewLinkableEvents(func(self *Events) (linker func(*Events)) {
	self.Tangle = tangle.NewEvents()

	return func(newTarget *Events) {
		self.Tangle.LinkTo(newTarget.Tangle)
	}
})
