// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "7960f7a7c6691afb5f07d4c30819cea6"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"629fe427503e5cf1bfa49722d21395a0": "1f8b08000000000000ff5491d14fc23010c6dff757d4be1a56718ba0e9f622898684101023fad6b565adaebda53d26fbef0d0e34f4a577dfefcb97cb1dbf5220b16f3531e89a32e1e74f0b55268410c29d4641a411216a2ce81e77a3293d21b4d8e8f2095e8c754e073213d1542082e26c4083adb1feebb73abfa09b8246ec1b1d8dd6482fa0097a575083d8c607c69c3848e5d30a002306d11e1b098efd092c4fb374cc648cff5aeaac4f658c97c1d6a3ae83c5bea0d1886c9a8fea7ad9af6fecf6b15aacba6c6b5b27b27c31bb56cf6cbc5b4da639fbbc93efccce37abd7a5916f6172b89f77b03e6c6e171fdfe3cd65be0c1023045b5b5f50e1c1f70ef6a719589970362c9557a0fa32e1ca76c4aa820600a42567ca7647d389b2e1103f010000ffff7280bcd7a0010000",
		"cb5bbc1beeeef73181bb7fdcb9f346dd": "1f8b08000000000000ff5cce310ec2300c85e13d52ee600ed06e2ce9c601b8439a98d622d891315511eadd19c840bbfeef0d9f777d555caeb8dae565260c1fef00000c57eb3226d168241c8085114ef4a8a216d986df2d49110d309698ee2dd59833f1d415bc5980735d0f5d699a77c3826a9462e962a189032464431dfe1cc761f3cebb7ea69cb181177ad24885ec1da0f59d75fb060000ffffdbb04808e9000000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr


	func() {
		b := packr.New("SPA_Assets", "./frontend/src/assets")
		b.SetResolver("index.html", packr.Pointer{ForwardBox: gk, ForwardPath: "629fe427503e5cf1bfa49722d21395a0"})
		b.SetResolver("main.css", packr.Pointer{ForwardBox: gk, ForwardPath: "cb5bbc1beeeef73181bb7fdcb9f346dd"})
	}()
	return nil
}()
