// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: packages/network/models/message.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Packet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Body:
	//
	//	*Packet_Block
	//	*Packet_BlockRequest
	//	*Packet_SlotCommitment
	//	*Packet_SlotCommitmentRequest
	//	*Packet_Attestations
	//	*Packet_AttestationsRequest
	Body isPacket_Body `protobuf_oneof:"body"`
}

func (x *Packet) Reset() {
	*x = Packet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packages_network_models_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_packages_network_models_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_packages_network_models_message_proto_rawDescGZIP(), []int{0}
}

func (m *Packet) GetBody() isPacket_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *Packet) GetBlock() *Block {
	if x, ok := x.GetBody().(*Packet_Block); ok {
		return x.Block
	}
	return nil
}

func (x *Packet) GetBlockRequest() *BlockRequest {
	if x, ok := x.GetBody().(*Packet_BlockRequest); ok {
		return x.BlockRequest
	}
	return nil
}

func (x *Packet) GetSlotCommitment() *SlotCommitment {
	if x, ok := x.GetBody().(*Packet_SlotCommitment); ok {
		return x.SlotCommitment
	}
	return nil
}

func (x *Packet) GetSlotCommitmentRequest() *SlotCommitmentRequest {
	if x, ok := x.GetBody().(*Packet_SlotCommitmentRequest); ok {
		return x.SlotCommitmentRequest
	}
	return nil
}

func (x *Packet) GetAttestations() *Attestations {
	if x, ok := x.GetBody().(*Packet_Attestations); ok {
		return x.Attestations
	}
	return nil
}

func (x *Packet) GetAttestationsRequest() *AttestationsRequest {
	if x, ok := x.GetBody().(*Packet_AttestationsRequest); ok {
		return x.AttestationsRequest
	}
	return nil
}

type isPacket_Body interface {
	isPacket_Body()
}

type Packet_Block struct {
	Block *Block `protobuf:"bytes,1,opt,name=block,proto3,oneof"`
}

type Packet_BlockRequest struct {
	BlockRequest *BlockRequest `protobuf:"bytes,2,opt,name=blockRequest,proto3,oneof"`
}

type Packet_SlotCommitment struct {
	SlotCommitment *SlotCommitment `protobuf:"bytes,3,opt,name=slotCommitment,proto3,oneof"`
}

type Packet_SlotCommitmentRequest struct {
	SlotCommitmentRequest *SlotCommitmentRequest `protobuf:"bytes,4,opt,name=slotCommitmentRequest,proto3,oneof"`
}

type Packet_Attestations struct {
	Attestations *Attestations `protobuf:"bytes,5,opt,name=attestations,proto3,oneof"`
}

type Packet_AttestationsRequest struct {
	AttestationsRequest *AttestationsRequest `protobuf:"bytes,6,opt,name=attestationsRequest,proto3,oneof"`
}

func (*Packet_Block) isPacket_Body() {}

func (*Packet_BlockRequest) isPacket_Body() {}

func (*Packet_SlotCommitment) isPacket_Body() {}

func (*Packet_SlotCommitmentRequest) isPacket_Body() {}

func (*Packet_Attestations) isPacket_Body() {}

func (*Packet_AttestationsRequest) isPacket_Body() {}

type Block struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bytes []byte `protobuf:"bytes,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
}

func (x *Block) Reset() {
	*x = Block{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packages_network_models_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_packages_network_models_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_packages_network_models_message_proto_rawDescGZIP(), []int{1}
}

func (x *Block) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

type BlockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *BlockRequest) Reset() {
	*x = BlockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packages_network_models_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockRequest) ProtoMessage() {}

func (x *BlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_network_models_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockRequest.ProtoReflect.Descriptor instead.
func (*BlockRequest) Descriptor() ([]byte, []int) {
	return file_packages_network_models_message_proto_rawDescGZIP(), []int{2}
}

func (x *BlockRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type SlotCommitment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bytes []byte `protobuf:"bytes,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
}

func (x *SlotCommitment) Reset() {
	*x = SlotCommitment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packages_network_models_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlotCommitment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotCommitment) ProtoMessage() {}

func (x *SlotCommitment) ProtoReflect() protoreflect.Message {
	mi := &file_packages_network_models_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotCommitment.ProtoReflect.Descriptor instead.
func (*SlotCommitment) Descriptor() ([]byte, []int) {
	return file_packages_network_models_message_proto_rawDescGZIP(), []int{3}
}

func (x *SlotCommitment) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

type SlotCommitmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *SlotCommitmentRequest) Reset() {
	*x = SlotCommitmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packages_network_models_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlotCommitmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotCommitmentRequest) ProtoMessage() {}

func (x *SlotCommitmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_network_models_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotCommitmentRequest.ProtoReflect.Descriptor instead.
func (*SlotCommitmentRequest) Descriptor() ([]byte, []int) {
	return file_packages_network_models_message_proto_rawDescGZIP(), []int{4}
}

func (x *SlotCommitmentRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type Attestations struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Commitment   []byte `protobuf:"bytes,1,opt,name=commitment,proto3" json:"commitment,omitempty"`
	BlocksIds    []byte `protobuf:"bytes,2,opt,name=blocks_ids,json=blocksIds,proto3" json:"blocks_ids,omitempty"`
	Attestations []byte `protobuf:"bytes,3,opt,name=attestations,proto3" json:"attestations,omitempty"`
}

func (x *Attestations) Reset() {
	*x = Attestations{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packages_network_models_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Attestations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attestations) ProtoMessage() {}

func (x *Attestations) ProtoReflect() protoreflect.Message {
	mi := &file_packages_network_models_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attestations.ProtoReflect.Descriptor instead.
func (*Attestations) Descriptor() ([]byte, []int) {
	return file_packages_network_models_message_proto_rawDescGZIP(), []int{5}
}

func (x *Attestations) GetCommitment() []byte {
	if x != nil {
		return x.Commitment
	}
	return nil
}

func (x *Attestations) GetBlocksIds() []byte {
	if x != nil {
		return x.BlocksIds
	}
	return nil
}

func (x *Attestations) GetAttestations() []byte {
	if x != nil {
		return x.Attestations
	}
	return nil
}

type AttestationsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Commitment []byte `protobuf:"bytes,1,opt,name=commitment,proto3" json:"commitment,omitempty"`
	EndIndex   []byte `protobuf:"bytes,2,opt,name=end_index,json=endIndex,proto3" json:"end_index,omitempty"`
}

func (x *AttestationsRequest) Reset() {
	*x = AttestationsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packages_network_models_message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttestationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestationsRequest) ProtoMessage() {}

func (x *AttestationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_network_models_message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestationsRequest.ProtoReflect.Descriptor instead.
func (*AttestationsRequest) Descriptor() ([]byte, []int) {
	return file_packages_network_models_message_proto_rawDescGZIP(), []int{6}
}

func (x *AttestationsRequest) GetCommitment() []byte {
	if x != nil {
		return x.Commitment
	}
	return nil
}

func (x *AttestationsRequest) GetEndIndex() []byte {
	if x != nil {
		return x.EndIndex
	}
	return nil
}

var File_packages_network_models_message_proto protoreflect.FileDescriptor

var file_packages_network_models_message_proto_rawDesc = []byte{
	0x0a, 0x25, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x22,
	0x99, 0x03, 0x0a, 0x06, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x25, 0x0a, 0x05, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x12, 0x3a, 0x0a, 0x0c, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52,
	0x0c, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x40, 0x0a,
	0x0e, 0x73, 0x6c, 0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x53,
	0x6c, 0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52,
	0x0e, 0x73, 0x6c, 0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12,
	0x55, 0x0a, 0x15, 0x73, 0x6c, 0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x53, 0x6c, 0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52,
	0x15, 0x73, 0x6c, 0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x0c, 0x61, 0x74, 0x74, 0x65, 0x73, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x48, 0x00, 0x52, 0x0c, 0x61, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x4f, 0x0a, 0x13, 0x61, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x13,
	0x61, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x42, 0x06, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x1d, 0x0a, 0x05, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x22, 0x1e, 0x0a, 0x0c, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x22, 0x26, 0x0a, 0x0e, 0x53, 0x6c,
	0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x62, 0x79, 0x74,
	0x65, 0x73, 0x22, 0x27, 0x0a, 0x15, 0x53, 0x6c, 0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x22, 0x71, 0x0a, 0x0c, 0x41,
	0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x63,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x49, 0x64, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x74,
	0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0c, 0x61, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x52,
	0x0a, 0x13, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x6e, 0x64, 0x5f, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x69, 0x6f, 0x74, 0x61, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2f, 0x67, 0x6f, 0x73, 0x68,
	0x69, 0x6d, 0x6d, 0x65, 0x72, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_packages_network_models_message_proto_rawDescOnce sync.Once
	file_packages_network_models_message_proto_rawDescData = file_packages_network_models_message_proto_rawDesc
)

func file_packages_network_models_message_proto_rawDescGZIP() []byte {
	file_packages_network_models_message_proto_rawDescOnce.Do(func() {
		file_packages_network_models_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_packages_network_models_message_proto_rawDescData)
	})
	return file_packages_network_models_message_proto_rawDescData
}

var file_packages_network_models_message_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_packages_network_models_message_proto_goTypes = []interface{}{
	(*Packet)(nil),                // 0: models.Packet
	(*Block)(nil),                 // 1: models.Block
	(*BlockRequest)(nil),          // 2: models.BlockRequest
	(*SlotCommitment)(nil),        // 3: models.SlotCommitment
	(*SlotCommitmentRequest)(nil), // 4: models.SlotCommitmentRequest
	(*Attestations)(nil),          // 5: models.Attestations
	(*AttestationsRequest)(nil),   // 6: models.AttestationsRequest
}
var file_packages_network_models_message_proto_depIdxs = []int32{
	1, // 0: models.Packet.block:type_name -> models.Block
	2, // 1: models.Packet.blockRequest:type_name -> models.BlockRequest
	3, // 2: models.Packet.slotCommitment:type_name -> models.SlotCommitment
	4, // 3: models.Packet.slotCommitmentRequest:type_name -> models.SlotCommitmentRequest
	5, // 4: models.Packet.attestations:type_name -> models.Attestations
	6, // 5: models.Packet.attestationsRequest:type_name -> models.AttestationsRequest
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_packages_network_models_message_proto_init() }
func file_packages_network_models_message_proto_init() {
	if File_packages_network_models_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_packages_network_models_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Packet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packages_network_models_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Block); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packages_network_models_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packages_network_models_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlotCommitment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packages_network_models_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlotCommitmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packages_network_models_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Attestations); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packages_network_models_message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttestationsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_packages_network_models_message_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Packet_Block)(nil),
		(*Packet_BlockRequest)(nil),
		(*Packet_SlotCommitment)(nil),
		(*Packet_SlotCommitmentRequest)(nil),
		(*Packet_Attestations)(nil),
		(*Packet_AttestationsRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_packages_network_models_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packages_network_models_message_proto_goTypes,
		DependencyIndexes: file_packages_network_models_message_proto_depIdxs,
		MessageInfos:      file_packages_network_models_message_proto_msgTypes,
	}.Build()
	File_packages_network_models_message_proto = out.File
	file_packages_network_models_message_proto_rawDesc = nil
	file_packages_network_models_message_proto_goTypes = nil
	file_packages_network_models_message_proto_depIdxs = nil
}
