package blockissuer

import (
	"github.com/iotaledger/hive.go/core/generics/event"

	"github.com/iotaledger/goshimmer/packages/protocol/models"
)

// Events represents events happening on a block factory.
type Events struct {

	// Triggered when a block is issued, i.e. sent to the protocol to be processed.
	BlockIssued *event.Linkable[*models.Block]

	// Fired when an error occurred.
	Error *event.Linkable[error]

	event.LinkableCollection[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.LinkableConstructor(func() (newEvents *Events) {
	return &Events{
		BlockIssued: event.NewLinkable[*models.Block](),
		Error:       event.NewLinkable[error](),
	}
})
