package clock

import (
	"time"

	"github.com/iotaledger/hive.go/core/generics/event"
)

// Events is a collection of events that can be triggered by the Clock.
type Events struct {
	// AcceptanceTimeUpdated is triggered when a Acceptance Tangle Time advances.
	AcceptanceTimeUpdated *event.Linkable[*TimeUpdateEvent]

	// AcceptanceTimeUpdated is triggered when a Acceptance Tangle Time advances.
	ConfirmedTimeUpdated *event.Linkable[*TimeUpdateEvent]

	// LinkableCollection is a generic trait that allows to link multiple collections of events together.
	event.LinkableCollection[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.LinkableConstructor(func() (newEvents *Events) {
	return &Events{
		ConfirmedTimeUpdated:  event.NewLinkable[*TimeUpdateEvent](),
		AcceptanceTimeUpdated: event.NewLinkable[*TimeUpdateEvent](),
	}
})

// TimeUpdateEvent represents an update of the clock.
type TimeUpdateEvent struct {
	// NewTime contains the time value that was set.
	NewTime time.Time

	// UpdateTime contains the wall clock time when the update occurred.
	UpdateTime time.Time
}
