package clock

import (
	"time"

	"github.com/iotaledger/hive.go/runtime/event"
)

// Events is a collection of events that can be triggered by the Clock.
type Events struct {
	// AcceptanceTimeUpdated is an Event with the following signature func(newTime time.Time, now time.Time).
	AcceptanceTimeUpdated *event.Event2[time.Time, time.Time]

	// AcceptanceTimeUpdated is triggered when a Acceptance Tangle Time advances.
	ConfirmedTimeUpdated *event.Event2[time.Time, time.Time]

	// LinkableCollection is a generic trait that allows to link multiple collections of events together.
	event.Group[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.CreateGroupConstructor(func() (newEvents *Events) {
	return &Events{
		ConfirmedTimeUpdated:  event.New2[time.Time, time.Time](),
		AcceptanceTimeUpdated: event.New2[time.Time, time.Time](),
	}
})

// TimeUpdateEvent represents an update of the clock.
type TimeUpdateEvent struct {
	// NewTime contains the time value that was set.
	NewTime time.Time

	// UpdateTime contains the wall clock time when the update occurred.
	UpdateTime time.Time
}
