name: Develop
'on':
  push:
    branches:
      - develop
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: iotaledger/goshimmer
          username: '${{ secrets.IOTALEDGER_HUB_DOCKER_LOGIN }}'
          password: '${{ secrets.IOTALEDGER_HUB_DOCKER_PASSWORD }}'
          tags: develop
