name: Publish Docker develop

on:
  push:
    branches:
    - develop

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@master

    - name: Publish to registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: iotagoshimmer/goshimmer
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "develop"
