name: Build image version with specific tag
on:
    workflow_dispatch:
      inputs:
        tagName:
          description: 'Tag name'
          required: true

jobs:
  docker:
    environment: devnet
    name: Docker build and push
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: "refs/tags/${{github.event.inputs.tagName}}"
      - name: Publish to Docker Hub
        uses: docker/build-push-action@92e71463491f2d026a477188b8ad3a0fdd9d672c
        env:
          DOCKER_BUILDKIT: 1
        with:
          repository: iotaledger/goshimmer
          username: '${{ secrets.IOTALEDGER_HUB_DOCKER_LOGIN }}'
          password: '${{ secrets.IOTALEDGER_HUB_DOCKER_PASSWORD }}'
          tags: ${{github.event.inputs.tagName}}
          build-args: DOWNLOAD_SNAPSHOT=0