package eviction

import (
	"github.com/iotaledger/hive.go/core/generics/event"

	"github.com/iotaledger/goshimmer/packages/core/epoch"
)

type Events struct {
	EpochEvicted *event.Linkable[epoch.Index, Events, *Events]

	event.LinkableCollection[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.NewLinkableEvents(func(self *Events) (linker func(*Events)) {
	self.EpochEvicted = event.NewLinkable[epoch.Index, Events]()

	return func(newTarget *Events) {
		self.EpochEvicted.LinkTo(newTarget.EpochEvicted)
	}
})
